// @ts-nocheck -- faithful port from Deno JavaScript; remove during typed cleanup.
// Ported from the original hosted autoBrollPopulate function
// Generated by migration/tools/port-fn.mjs ; runtime adaptations reviewed.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import { geminiFetch } from '../lib/ai';
import { rankStockClips } from '../lib/brollRanking';
import type { FnHandler } from '../types';


// ══════════════════════════════════════════════════════════════════
// AUTO B-ROLL POPULATE
// AI-driven service that:
//  1. Reads all scenes from a project
//  2. Uses Gemini to extract optimal search queries per scene
//  3. Searches Pexels + Pixabay in parallel for each query
//  4. Ranks results by relevance and populates scene records
// ══════════════════════════════════════════════════════════════════

const BATCH_SIZE = 10; // Scenes per Gemini call
const MAX_SCENES_PER_CALL = 20; // Limit per invocation to avoid timeout

async function callGemini(ctx, prompt, temperature = 0.3) {
  const response = await geminiFetch(ctx, '/v1beta/models/gemini-2.0-flash:generateContent', {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: { temperature, maxOutputTokens: 4096, responseMimeType: "application/json" }
      })
    });
  if (!response.ok) {
    const err = await response.json();
    throw new Error(`Gemini ${response.status}: ${err.error?.message || "Unknown"}`);
  }
  const data = await response.json();
  const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text || '{}';
  try { return JSON.parse(rawText); } catch (_) {
    const cleaned = rawText.replace(/```json\s*/g, '').replace(/```\s*/g, '');
    return JSON.parse(cleaned);
  }
}

// `problems` collects why a search came back empty. Without it a missing key or a
// rate-limited provider looked exactly like "no footage exists for this scene".
async function searchPexels(ctx, query, orientation, problems = []) {
  const apiKey = await ctx.keys.get('PEXELS_API_KEY');
  if (!apiKey) return [];
  const params = new URLSearchParams({
    query, per_page: '8', page: '1',
    orientation: orientation === 'portrait' ? 'portrait' : 'landscape',
  });
  try {
    const res = await fetch(`https://api.pexels.com/videos/search?${params}`, {
      headers: { 'Authorization': apiKey }
    });
    if (!res.ok) {
      problems.push(res.status === 401 || res.status === 403
        ? 'Pexels rejected the API key'
        : `Pexels answered HTTP ${res.status}`);
      return [];
    }
    const data = await res.json();
    return (data.videos || []).map(v => {
      const files = v.video_files || [];
      const hd = files.find(f => f.quality === 'hd' && f.width >= 1280);
      const sd = files.find(f => f.quality === 'sd');
      const best = hd || sd || files[0];
      return {
        id: `pexels-${v.id}`,
        source: 'pexels',
        name: v.url?.split('/').pop()?.replace(/-/g, ' ') || '',
        thumbnail: v.image,
        downloadUrl: best?.link,
        duration: v.duration,
        width: best?.width,
        height: best?.height,
        author: v.user?.name,
      };
    });
  } catch (e) { problems.push(`Pexels: ${e.message}`); console.warn('Pexels error:', e.message); return []; }
}

async function searchPixabay(ctx, query, problems = []) {
  const apiKey = await ctx.keys.get('PIXABAY_API_KEY');
  if (!apiKey) return [];
  const params = new URLSearchParams({
    key: apiKey, q: query, video_type: 'film',
    per_page: '8', safesearch: 'true', order: 'popular',
  });
  try {
    const res = await fetch(`https://pixabay.com/api/videos/?${params}`);
    if (!res.ok) {
      problems.push(res.status === 400 || res.status === 401
        ? 'Pixabay rejected the API key'
        : `Pixabay answered HTTP ${res.status}`);
      return [];
    }
    const data = await res.json();
    return (data.hits || []).map(v => {
      const vids = v.videos || {};
      const best = vids.large || vids.medium || vids.small || {};
      return {
        id: `pixabay-${v.id}`,
        source: 'pixabay',
        name: v.tags || '',
        thumbnail: v.picture_id ? `https://i.vimeocdn.com/video/${v.picture_id}_295x166.jpg` : '',
        downloadUrl: best.url,
        duration: v.duration,
        width: best.width,
        height: best.height,
        author: v.user,
      };
    });
  } catch (e) { problems.push(`Pixabay: ${e.message}`); console.warn('Pixabay error:', e.message); return []; }
}

/** The breakdown stores its shot notes as a DIRECTOR_NOTES: prefix on image_prompt. */
function directorNotes(scene) {
  const raw = scene?.image_prompt;
  if (typeof raw !== 'string' || !raw.startsWith('DIRECTOR_NOTES:')) return {};
  try { return JSON.parse(raw.slice(15)) || {}; } catch (_) { return {}; }
}

const handler: FnHandler = async (body, ctx) => {
  try {
    const user = ctx.user;

    const { project_id } = body;
    if (!project_id) throw new HttpError(400, 'project_id required');

    const [projects, allScenes] = await Promise.all([
      ctx.db.Projects.filter({ id: project_id }),
      ctx.db.Scenes.filter({ project_id }),
    ]);

    const project = projects[0];
    if (!project) throw new HttpError(404, 'Project not found');

    const allEligible = allScenes
      .filter(s => s.narration_text?.trim())
      .sort((a, b) => a.scene_number - b.scene_number);

    // Only process scenes that don't already have b-roll
    const unpopulated = allEligible.filter(s => !s.broll_url || !s.broll_url.startsWith('http'));
    
    if (unpopulated.length === 0) {
      return { success: true, done: true, populated: 0, total: allEligible.length, message: 'All scenes already have B-roll' };
    }

    // Limit per call to avoid platform timeout
    const scenes = unpopulated.slice(0, MAX_SCENES_PER_CALL);
    const hasMore = unpopulated.length > MAX_SCENES_PER_CALL;

    const orientation = project.orientation || 'landscape';
    const niche = project.niche || 'general';

    // Both searches used to return an empty list when their key was missing, so a project
    // with no stock provider reported "0 scenes matched" and looked like a search miss.
    const [pexelsKey, pixabayKey] = await Promise.all([
      ctx.keys.get('PEXELS_API_KEY'),
      ctx.keys.get('PIXABAY_API_KEY'),
    ]);
    if (!pexelsKey && !pixabayKey) {
      throw new HttpError(400, 'No stock footage provider is set up. Add a Pexels API key under Settings → API Keys (Pixabay is optional) and run Auto B-Roll again.');
    }
    const problems: string[] = [];

    console.log(`🎬 Auto B-Roll: ${scenes.length} scenes | niche: ${niche} | orientation: ${orientation}`);

    // Process scenes in batches through Gemini
    let totalPopulated = 0;
    const results = [];

    for (let batchStart = 0; batchStart < scenes.length; batchStart += BATCH_SIZE) {
      const batch = scenes.slice(batchStart, batchStart + BATCH_SIZE);

      // Step 1: Ask Gemini to generate optimal search queries
      // Mood and environment used to be read off the Scene row, where neither field
      // exists — both were always undefined, and the prompt dropped them anyway. They
      // come from the breakdown's director notes.
      const sceneSummaries = batch.map(s => {
        const notes = directorNotes(s);
        return {
          scene_number: s.scene_number,
          narration: (s.narration_text || '').substring(0, 300),
          visual: (notes.visual_description || notes.visual_concept || '').substring(0, 200),
          mood: [notes.mood, notes.lighting, notes.color_palette].filter(Boolean).join(', ').substring(0, 120),
        };
      });

      const geminiPrompt = `You are a B-roll video researcher for a ${niche} YouTube channel.

For each scene below, generate 2 search queries optimized for stock video sites (Pexels, Pixabay).
The queries should find GENERIC, ATMOSPHERIC footage — NOT specific people or branded content.
Focus on: environments, moods, textures, nature, abstract visuals, establishing shots.

RULES:
- Queries must be 2-5 words each (stock sites work best with short queries)
- First query: the PRIMARY visual concept (e.g. "city skyline night", "ocean waves sunset")
- Second query: an ALTERNATIVE angle or metaphor (e.g. "lonely street rain", "golden light window")
- Avoid: character names, specific brands, complex scenes that stock footage won't have
- Think about what would LOOK GOOD as background footage while someone narrates

SCENES:
${sceneSummaries.map(s => [
  `Scene ${s.scene_number}: "${s.narration}"`,
  s.visual ? `  Shot the director asked for: ${s.visual}` : '',
  s.mood ? `  Mood and light: ${s.mood}` : '',
].filter(Boolean).join('\n')).join('\n')}

Return JSON:
{
  "queries": [
    {"scene_number": 1, "primary": "ocean waves sunset", "alternative": "golden horizon calm"},
    ...
  ]
}`;

      let queries;
      try {
        const geminiResult = await callGemini(ctx, geminiPrompt);
        queries = geminiResult.queries || [];
      } catch (err) {
        console.warn(`Gemini batch error: ${err.message} — falling back to narration keywords`);
        // Fallback: extract first 4 words from narration
        queries = batch.map(s => ({
          scene_number: s.scene_number,
          primary: (s.narration_text || '').split(/\s+/).slice(0, 4).join(' '),
          alternative: niche + ' background',
        }));
      }

      // Step 2: Search Pexels + Pixabay for each scene
      const searchPromises = batch.map(async (scene) => {
        const q = queries.find(q => q.scene_number === scene.scene_number);
        if (!q) return { scene, videos: [] };

        // Search both queries across both sources in parallel
        const [pexPrimary, pixPrimary, pexAlt, pixAlt] = await Promise.all([
          searchPexels(ctx, q.primary, orientation, problems),
          searchPixabay(ctx, q.primary, problems),
          searchPexels(ctx, q.alternative, orientation, problems),
          searchPixabay(ctx, q.alternative, problems),
        ]);

        // Merge and deduplicate. Results for the primary query are marked so the ranking
        // can prefer them over the fallback angle.
        const allVideos = [
          ...pexPrimary.map(v => ({ ...v, fromPrimary: true })),
          ...pixPrimary.map(v => ({ ...v, fromPrimary: true })),
          ...pexAlt,
          ...pixAlt,
        ];
        const seen = new Set();
        const unique = allVideos.filter(v => {
          if (!v.downloadUrl || seen.has(v.downloadUrl)) return false;
          seen.add(v.downloadUrl);
          return true;
        });

        // Rank for THIS scene: cover its length, match its shape, then look sharp.
        const ranked = rankStockClips(unique, {
          neededSeconds: Number(scene.duration_seconds) || 5,
          portrait: orientation === 'portrait',
        });

        return {
          scene,
          videos: ranked.slice(0, 3), // Top 3 candidates
          query: q,
        };
      });

      const batchResults = await Promise.all(searchPromises);

      // Step 3: Update scene records with best B-roll match
      for (const { scene, videos, query } of batchResults) {
        const best = videos[0];
        if (!best || !best.downloadUrl) {
          results.push({
            scene_number: scene.scene_number,
            status: 'no_match',
            query: query?.primary,
          });
          continue;
        }

        // Store B-roll data in dedicated scene fields
        try {
          await ctx.db.Scenes.update(scene.id, {
            broll_url: best.downloadUrl,
            broll_source: best.source,
            broll_id: best.id,
            broll_thumbnail: best.thumbnail || '',
            broll_query: query?.primary || '',
          });
          totalPopulated++;
          results.push({
            scene_number: scene.scene_number,
            status: 'populated',
            source: best.source,
            query: query?.primary,
            url: best.downloadUrl?.substring(0, 80),
          });
        } catch (err) {
          console.warn(`Failed to update scene ${scene.scene_number}:`, err.message);
          results.push({
            scene_number: scene.scene_number,
            status: 'error',
            error: err.message,
          });
        }
      }

      console.log(`✓ Batch ${Math.floor(batchStart / BATCH_SIZE) + 1}: ${batchResults.filter(r => r.videos.length > 0).length}/${batch.length} scenes matched`);

      // Rate limit courtesy
      if (batchStart + BATCH_SIZE < scenes.length) {
        await new Promise(r => setTimeout(r, 1000));
      }
    }

    console.log(`🎉 Auto B-Roll complete: ${totalPopulated}/${scenes.length} scenes populated`);

    return {
      success: true,
      done: !hasMore,
      populated: totalPopulated,
      total: allEligible.length,
      remaining: hasMore ? unpopulated.length - scenes.length : 0,
      // What went wrong upstream, so "0 scenes matched" can say why.
      warnings: [...new Set(problems)].slice(0, 5),
      results,
    };
  } catch (error) {
    console.error('autoBrollPopulate error:', error.message);
    // A 400 that explains a missing key must not be flattened into a 500.
    throw error instanceof HttpError ? error : new HttpError(500, error.message);
  }
};

export default handler;
