// @ts-nocheck — legacy port; runtime contracts are covered by Phase 8 tests.
// Ported from the original hosted checkMusicStatus function
// Generated by migration/tools/port-fn.mjs; Phase 8 manual follow-ups resolved.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import { getTask } from '../lib/ai33';
import { ingestUrl } from '../lib/r2';
import type { FnHandler } from '../types';

const handler: FnHandler = async (body, ctx) => {
  try {
    const user = ctx.user;

    const { task_id, track_id } = body;

    if (!task_id) throw new HttpError(400, 'Missing task_id');

    const task = await getTask(ctx, task_id);

    if (task.status === 'error') {
      if (track_id) await ctx.db.MusicTracks.update(track_id, { status: 'failed' });
      return { status: 'FAILED', error: task.error || 'Music generation failed' };
    }
    if (task.status !== 'done' || !task.audioUrl) {
      return { status: 'PROCESSING', progress: task.progress, stream_url: task.streamUrl };
    }

    const firstClip = task.raw?.metadata?.suno_result?.clips?.[0] || {};
    const duration = Number(firstClip.duration || task.raw?.metadata?.duration || 0);
    const stored = await ingestUrl(ctx, task.audioUrl, {
      tier: 'durable',
      prefix: 'music',
      filename: track_id ? `${track_id}-${Date.now()}.mp3` : undefined,
    });

    if (track_id) {
      await ctx.db.MusicTracks.update(track_id, {
        audio_url: stored.url,
        status: 'completed',
        duration_seconds: Math.round(duration) || 120,
      });
    }

    // MusicPanel stops polling only on COMPLETED/FAILED. Keep that live contract even
    // though the provider's internal completion vocabulary is `done`.
    return { status: 'COMPLETED', audio_url: stored.url, duration };

  } catch (error) {
    console.error('checkMusicStatus error:', error.message);
    throw new HttpError(500, error.message);
  }
};

export default handler;
