// Ported from the original hosted detectFaceRegion function
// @ts-nocheck — temporary Phase 7 port debt; runtime behavior is preserved verbatim.
// Generated by migration/tools/port-fn.mjs; Phase 7 port review completed.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import { geminiFetch } from '../lib/ai';
import type { FnHandler } from '../types';


// ══════════════════════════════════════════════════════════════════
// DETECT FACE REGION — Claude Vision face detection for smart crop
//
// Input:  { image_url } — URL of a video frame screenshot
//         OR { image_base64 } — base64 encoded frame
// Output: { faces: [...], primary_face: { x_center_percent, y_center_percent, ... } }
//
// Used by ExportEngine to position the 9:16 crop window so the
// speaker stays centered both horizontally AND vertically.
// ══════════════════════════════════════════════════════════════════

function clamp(n: number, lo = 0, hi = 100) {
  if (!Number.isFinite(n)) return 50;
  return Math.max(lo, Math.min(hi, n));
}

const handler: FnHandler = async (body, ctx) => {
  try {
    const user = ctx.user;

    const { image_url, image_base64 } = body;

    if (!image_url && !image_base64) {
      throw new HttpError(400, 'image_url or image_base64 required');
    }

    const apiKey = await ctx.keys.get('GEMINI_API_KEY');
    if (!apiKey) throw new HttpError(500, 'GEMINI_API_KEY not configured');

    // Build inline image data for Gemini
    let b64 = image_base64;
    if (!b64) {
      const imgRes = await fetch(image_url);
      if (!imgRes.ok) throw new Error(`Failed to fetch image: ${imgRes.status}`);
      const bytes = new Uint8Array(await imgRes.arrayBuffer());
      let binary = '';
      const CHUNK = 8192;
      for (let i = 0; i < bytes.length; i += CHUNK) {
        binary += String.fromCharCode(...bytes.subarray(i, i + CHUNK));
      }
      b64 = btoa(binary);
    }

    const systemPrompt = `You are a computer-vision assistant specialized in detecting human faces in video frames for 9:16 vertical reframing.

Your job: find the person most likely speaking to the camera — the "primary subject" — and report the CENTER of their face as a percentage of the image width/height.

Rules:
- If multiple people are visible, pick the one with the largest face OR the one whose mouth appears open / who looks engaged with the camera.
- If no face is visible, return an empty faces array.
- Values are PERCENTAGES (0-100) of the image dimensions, where (0,0) is the top-left corner.
- Return ONLY valid JSON, no prose.`;

    const userPrompt = `Analyze this video frame and return the face position.

Return this exact JSON shape:
{
  "faces": [
    {
      "x_center_percent": 52,
      "y_center_percent": 38,
      "width_percent": 14,
      "height_percent": 20,
      "is_speaking": true
    }
  ]
}

If no faces: { "faces": [] }`;

    const response = await geminiFetch(ctx, '/v1beta/models/gemini-2.5-flash:generateContent', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{
            parts: [
              { inline_data: { mime_type: 'image/jpeg', data: b64 } },
              { text: systemPrompt + '\n\n' + userPrompt },
            ],
          }],
          generationConfig: { temperature: 0.1, maxOutputTokens: 2048, thinkingConfig: { thinkingBudget: 0 } },
        }),
      });

    if (!response.ok) {
      const err = await response.json();
      throw new Error(`Gemini API Error ${response.status}: ${err.error?.message || 'Unknown'}`);
    }

    const data = await response.json();
    const text = data.candidates?.[0]?.content?.parts?.[0]?.text || '';

    let jsonStr = text;
    if (text.includes('```json')) {
      jsonStr = text.split('```json')[1].split('```')[0].trim();
    } else if (text.includes('```')) {
      jsonStr = text.split('```')[1].split('```')[0].trim();
    }

    let result: any;
    try {
      result = JSON.parse(jsonStr);
    } catch (_e) {
      console.warn('Gemini returned unparseable response:', text.substring(0, 200));
      return { success: true, faces: [], primary_face: null, face_count: 0 };
    }

    const faces = Array.isArray(result.faces) ? result.faces : [];

    // Validate + normalize each face
    const validFaces = faces
      .map((f: any) => ({
        x_center_percent: clamp(Number(f.x_center_percent)),
        y_center_percent: clamp(Number(f.y_center_percent)),
        width_percent: clamp(Number(f.width_percent ?? 15), 1, 100),
        height_percent: clamp(Number(f.height_percent ?? 20), 1, 100),
        is_speaking: !!f.is_speaking,
      }))
      .filter((f: any) =>
        f.width_percent > 2 && f.height_percent > 2 && // not a dot
        f.x_center_percent > 0 && f.x_center_percent < 100 &&
        f.y_center_percent > 0 && f.y_center_percent < 100
      );

    // Pick primary: speaking > largest
    let primary = null;
    if (validFaces.length > 0) {
      const speaking = validFaces.find((f: any) => f.is_speaking);
      const largest = validFaces.reduce((a: any, b: any) =>
        (a.width_percent * a.height_percent) > (b.width_percent * b.height_percent) ? a : b
      );
      primary = speaking || largest;
    }

    console.log(`👤 Gemini detected ${validFaces.length} face(s)${primary ? `, primary at x=${primary.x_center_percent}% y=${primary.y_center_percent}%` : ''}`);

    return {
      success: true,
      faces: validFaces,
      primary_face: primary,
      face_count: validFaces.length,
    };

  } catch (error) {
    console.error('❌ detectFaceRegion error:', error.message);
    throw new HttpError(500, error.message);
  }
};

export default handler;
