// @ts-nocheck -- faithful port from Deno JavaScript; remove during typed cleanup.
// Ported from base44/functions/downloadYouTubeVideo.ts
// Generated by migration/tools/port-fn.mjs ; runtime adaptations reviewed.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import { ingestUrl } from '../lib/r2';
import type { FnHandler } from '../types';


// v2 — downloadYouTubeVideo using proven Cobalt pattern

const handler: FnHandler = async (body, ctx) => {
  const user = ctx.user;

  const { url } = body;
  if (!url) throw new HttpError(400, 'url required');

  const cobaltApiUrl = await ctx.keys.get('COBALT_API_URL');
  if (!cobaltApiUrl) throw new HttpError(400, 'COBALT_API_URL not set');

  const apiEndpoint = cobaltApiUrl.endsWith('/') ? cobaltApiUrl : cobaltApiUrl + '/';
  console.log('[DownloadYT] Cobalt endpoint: ' + apiEndpoint);
  console.log('[DownloadYT] URL: ' + url);

  // ── Step 1: Get VIDEO from Cobalt (for browser playback) ──────
  console.log('[DownloadYT] Requesting video...');
  const videoRes = await fetch(apiEndpoint, {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      url: url,
      videoQuality: '720',
      youtubeVideoCodec: 'h264',
      filenameStyle: 'basic',
    }),
  });

  console.log('[DownloadYT] Video response status: ' + videoRes.status);
  const videoText = await videoRes.text();
  console.log('[DownloadYT] Video response: ' + videoText.substring(0, 300));

  let videoData;
  try { videoData = JSON.parse(videoText); } catch { videoData = null; }

  let videoUrl = '';
  let videoFilename = '';
  if (videoData && (videoData.status === 'tunnel' || videoData.status === 'redirect' || videoData.status === 'stream')) {
    videoUrl = videoData.url || '';
    videoFilename = videoData.filename || '';
    console.log('[DownloadYT] Video URL obtained (' + videoData.status + ')');
  } else if (videoData && videoData.status === 'picker' && videoData.picker && videoData.picker.length > 0) {
    const item = videoData.picker.find(function(i) { return i.type === 'video'; }) || videoData.picker[0];
    videoUrl = item.url || '';
    console.log('[DownloadYT] Video from picker');
  } else {
    console.log('[DownloadYT] Video extraction failed: ' + (videoData?.error?.code || 'unknown'));
  }

  // ── Step 2: Get AUDIO from Cobalt (for ASR transcription) ─────
  console.log('[DownloadYT] Requesting audio...');
  const audioRes = await fetch(apiEndpoint, {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      url: url,
      downloadMode: 'audio',
      audioFormat: 'mp3',
      audioBitrate: '128',
    }),
  });

  console.log('[DownloadYT] Audio response status: ' + audioRes.status);
  const audioText = await audioRes.text();
  console.log('[DownloadYT] Audio response: ' + audioText.substring(0, 300));

  let audioData;
  try { audioData = JSON.parse(audioText); } catch { audioData = null; }

  let cobaltAudioUrl = '';
  if (audioData && (audioData.status === 'tunnel' || audioData.status === 'redirect' || audioData.status === 'stream')) {
    cobaltAudioUrl = audioData.url || '';
    console.log('[DownloadYT] Audio URL obtained (' + audioData.status + ')');
  } else if (audioData && audioData.status === 'picker' && audioData.picker && audioData.picker.length > 0) {
    const item = audioData.picker.find(function(i) { return i.type === 'audio'; }) || audioData.picker[0];
    cobaltAudioUrl = item.url || '';
    console.log('[DownloadYT] Audio from picker');
  }

  // Re-host the temporary Cobalt audio using the durable R2 adapter.
  let stableAudioUrl = cobaltAudioUrl;
  if (cobaltAudioUrl) {
    try {
      stableAudioUrl = (await ingestUrl(ctx, cobaltAudioUrl, { tier: 'durable', prefix: 'youtube', filename: 'audio.mp3' })).url;
    } catch (dlErr) {
      console.log('[DownloadYT] Audio download error: ' + dlErr.message);
    }
  }

  // ── Step 4: Get metadata from oEmbed ──────────────────────────
  // Cobalt video links are temporary too. Re-host the source video so clip
  // generation, browser preview, and cloud rendering all use the same stable URL.
  let stableVideoUrl = videoUrl;
  if (videoUrl) {
    try {
      console.log('[DownloadYT] Re-hosting source video for clipping...');
      stableVideoUrl = (await ingestUrl(ctx, videoUrl, { tier: 'durable', prefix: 'youtube', filename: videoFilename || 'youtube_video.mp4' })).url || videoUrl;
      console.log('[DownloadYT] Stable video URL: ' + stableVideoUrl.substring(0, 80));
    } catch (videoErr) {
      console.log('[DownloadYT] Video rehost failed, using original Cobalt URL: ' + videoErr.message);
    }
  }

  let title = videoFilename ? videoFilename.replace(/\.[^.]+$/, '') : '';
  let channel = '';
  let videoId = '';

  const idMatch = url.match(/(?:watch\?v=|youtu\.be\/|shorts\/)([a-zA-Z0-9_-]{11})/);
  if (idMatch) videoId = idMatch[1];

  if (videoId) {
    try {
      const oembedRes = await fetch('https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=' + videoId + '&format=json');
      if (oembedRes.ok) {
        const oembedData = await oembedRes.json();
        title = oembedData.title || title;
        channel = oembedData.author_name || '';
      }
    } catch (e) {
      console.log('[DownloadYT] oEmbed failed: ' + e.message);
    }
  }

  // ── Return result ─────────────────────────────────────────────
  if (!videoUrl && !stableAudioUrl) {
    throw new HttpError(400, 'Could not extract video or audio from this URL. It may be private, age-restricted, or geo-blocked.',);
  }

  console.log('[DownloadYT] Done! video=' + (videoUrl ? 'yes' : 'no') + ' audio=' + (stableAudioUrl ? 'yes' : 'no'));

  return {
    success: true,
    video_url: stableVideoUrl || videoUrl,
    stable_video_url: stableVideoUrl || '',
    raw_video_url: videoUrl,
    audio_url: stableAudioUrl || videoUrl,
    stable_audio_url: stableAudioUrl || '',
    title: title,
    channel: channel,
    video_id: videoId,
    thumbnail: videoId ? ('https://img.youtube.com/vi/' + videoId + '/maxresdefault.jpg') : '',
  };
};

export default handler;
