// Ported from base44/functions/generateSceneVideo.ts
// @ts-nocheck — temporary Phase 7 port debt; runtime behavior is preserved verbatim.
// Generated by migration/tools/port-fn.mjs; Phase 7 port review completed.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import type { FnHandler } from '../types';

// v2 — redeployed

// ══════════════════════════════════════════════════════════════════
// SCENE VIDEO GENERATOR — Grok Imagine image-to-video via Kie API
// ══════════════════════════════════════════════════════════════════
// Generates animated video from scene still image using Grok Imagine.
// 480p, 6s clips. ~$0.10 per 6s video.
//
// REQUIRES: Scene must have a public HTTP image_url.
// ══════════════════════════════════════════════════════════════════

const KIE_BASE = "https://api.kie.ai/api/v1/jobs";

const handler: FnHandler = async (body, ctx) => {
  let scene_id;

  try {
    const user = ctx.user;

    
    scene_id = body.scene_id;

    const KIE_API_KEY = await ctx.keys.get('KIE_API_KEY');
    if (!KIE_API_KEY) throw new HttpError(500, 'KIE_API_KEY not configured');

    const scenes = await ctx.db.Scenes.filter({ id: scene_id });
    const scene = scenes[0];
    if (!scene) throw new HttpError(404, 'Scene not found');

    if (!scene.image_url) {
      throw new HttpError(400, 'Scene image must be generated first');
    }

    if (scene.image_url.startsWith('data:')) {
      throw new HttpError(400, 'Scene image is a data URI. Requires a public URL. Re-generate the scene image.');
    }

    if (!scene.image_url.startsWith('http')) {
      throw new HttpError(400, 'Scene image must be a public HTTP URL');
    }

    // Build animation prompt
    const prompt = scene.animation_prompt || "Subtle cinematic motion, slow camera movement";

    console.log(`🎬 Scene ${scene.scene_number} | Grok Imagine image-to-video | 480p`);
    console.log(`🖼️ Image: ${scene.image_url.substring(0, 80)}...`);
    console.log(`🎥 Prompt: ${prompt.substring(0, 120)}...`);

    // ══════════════════════════════════════════════════════════════
    // SUBMIT TO GROK IMAGINE IMAGE-TO-VIDEO VIA KIE
    // ══════════════════════════════════════════════════════════════

    const response = await fetch(`${KIE_BASE}/createTask`, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${KIE_API_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: "grok-imagine/image-to-video",
        input: {
          image_urls: [scene.image_url],
          prompt,
          mode: "normal",
          duration: "6",
          resolution: "480p"
        }
      })
    });

    const resText = await response.text();
    console.log(`Kie response (${response.status}): ${resText.substring(0, 300)}`);

    let resData;
    try {
      resData = JSON.parse(resText);
    } catch (e) {
      throw new Error("Kie returned non-JSON: " + resText.substring(0, 200));
    }

    if (!response.ok || resData.code !== 200) {
      throw new Error(`Kie API error: ${resData.message || resData.msg || resText.substring(0, 200)}`);
    }

    const taskId = resData.data?.taskId;
    if (!taskId) throw new Error("No taskId returned from Kie API");

    console.log(`✓ Grok video task created: ${taskId}`);

    // Store task reference on scene (grok_vid_task prefix to distinguish)
    await ctx.db.Scenes.update(scene_id, {
      video_url: `grok_vid_task:${taskId}`,
      status: "pending"
    });

    return {
      success: true,
      task_id: taskId,
      scene_number: scene.scene_number,
      provider: "grok-imagine/image-to-video",
      status: "CREATED"
    };

  } catch (error) {
    console.error("generateSceneVideo error:", error.message, error.stack);
    if (scene_id) {
      try {
        await ctx.db.Scenes.update(scene_id, { status: "failed" });
      } catch (_) {}
    }
    throw new HttpError(500, error.message);
  }
};

export default handler;
