// @ts-nocheck — legacy port; runtime contracts are covered by Phase 8 tests.
// Ported from the original hosted generateVoiceover function
// Generated by migration/tools/port-fn.mjs; Phase 8 manual follow-ups resolved.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import type { Ctx, FnHandler } from '../types';
import { stripTtsMarkers } from '../lib/scriptText';

// ══════════════════════════════════════════════════════════════════
// VOICEOVER GENERATOR — 3 Paths, No Fallback (v3)
//
// Path A: MiniMax Direct SYNC  (short scripts ≤ 5000 chars)
// Path B: MiniMax Direct ASYNC (long scripts, api.minimax.io/v1/t2a_async_v2)
// Path C: AI33 Pro ASYNC       (submit + poll via api.ai33.pro)
//
// No fallback. If selected service fails → return error to user.
// Frontend sends provider: 'minimax_direct' or 'ai33'
// ══════════════════════════════════════════════════════════════════

async function uploadToR2(ctx: Ctx, audioBytes: Uint8Array, fileName: string) {
  await ctx.env.MEDIA.put(fileName, audioBytes, {
    httpMetadata: { contentType: 'audio/mpeg' },
  });
  return `${ctx.env.MEDIA_PUBLIC_BASE.replace(/\/$/, '')}/${fileName}`;
}

function cleanScript(text, isSleepMode = false) {
  // Control tokens written for another TTS engine (<|prosody:long_pause|> and friends):
  // our voices have never heard of them and read them aloud.
  let cleaned = stripTtsMarkers(text);
  if (isSleepMode) {
    cleaned = cleaned.replace(/\[(PAUSE\s+(\d+)\s*(?:SEC(?:ONDS?)?)?)\]/gi, (_, _c, seconds) => {
      const sec = parseInt(seconds) || 3;
      const groups = Math.ceil(sec / 3);
      return ' ' + Array(groups).fill('... ... ...').join(' ') + ' ';
    });
    cleaned = cleaned.replace(/\[BREATHE\]/gi, ' ... ... ... ... ');
  } else {
    cleaned = cleaned.replace(/\[[^\]]*\]/gi, '');
  }
  cleaned = cleaned
    .replace(/^(VOICEOVER|NARRATOR|VO|SOUND|MUSIC|SFX|SCENE)\s*:\s*/gim, '')
    .replace(/\*\*[^*]+\*\*:?\s*/g, '')
    .replace(/\([^)]*(?:voiceover|pause|beat|whisper|dramatic)[^)]*\)/gi, '')
    .replace(/\(?\d{1,2}:\d{2}\s*[-–—]\s*\d{1,2}:\d{2}\)?/g, '')
    .replace(/#{1,6}\s+/g, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
  return cleaned;
}

async function saveSettings(ctx: Ctx, settings: any, project_id: string, payload: any) {
  if (settings) {
    await ctx.db.ProductionSettings.update(settings.id, payload);
  } else {
    await ctx.db.ProductionSettings.create(payload);
  }
}

const handler: FnHandler = async (body, ctx) => {
  try {
    const user = ctx.user;

    const { project_id, voice_id, voice_category, provider: requestedProvider } = body;
    if (!project_id) throw new HttpError(400, 'Missing project_id');

    const MINIMAX_KEY = await ctx.keys.get('MINIMAX_API_KEY');
    const AI33_KEY = await ctx.keys.get('AI33_API_KEY');

    // ── Load project + script ───────────────────────────────────
    const [projects, allScripts] = await Promise.all([
      ctx.db.Projects.filter({ id: project_id }),
      ctx.db.Scripts.filter({ project_id }),
    ]);
    const project = projects[0];
    if (!project) throw new HttpError(404, 'Project not found');

    const script = allScripts.find(s => s.version === 'final_aggregated');
    if (!script?.full_script) {
      throw new HttpError(400, 'No final_aggregated script found.');
    }

    const isSleepMode = project.project_mode === 'sleep_meditation' || project.project_mode === 'sleep_story';
    const cleanedText = cleanScript(script.full_script, isSleepMode);
    const wordCount = cleanedText.split(/\s+/).filter(w => w.length > 0).length;

    const defaultVoice = isSleepMode ? 'English_CalmWoman' : 'English_expressive_narrator';
    const selectedVoiceId = voice_id || defaultVoice;
    const useMinimax = requestedProvider === 'minimax_direct';

    
    // ── Load settings ───────────────────────────────────────────
    const settingsList = await ctx.db.ProductionSettings.filter({ project_id });
    const settings = settingsList[0];

    // ════════════════════════════════════════════════════════════
    // PATH A+B: MINIMAX DIRECT (sync or async based on length)
    // ════════════════════════════════════════════════════════════
    if (useMinimax) {
      if (!MINIMAX_KEY) {
        throw new HttpError(500, 'MINIMAX_API_KEY not configured. Switch to AI33.');
      }

      const isShort = cleanedText.length <= 5000;

      if (isShort) {
        // ── PATH A: MiniMax Direct SYNC (instant) ───────────────
        console.log(`📍 Path A: MiniMax SYNC — ${cleanedText.length} chars`);

        const response = await fetch('https://api.minimax.io/v1/t2a_v2', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${MINIMAX_KEY}`,
          },
          body: JSON.stringify({
            model: 'speech-2.8-hd',
            text: cleanedText,
            stream: false,
            voice_setting: { voice_id: selectedVoiceId, speed: 1.0, vol: 1.0, pitch: 0 },
            audio_setting: { sample_rate: 32000, bitrate: 128000, format: 'mp3', channel: 1 },
            output_format: 'hex',
          }),
        });

        const data = await response.json();

        if (data.base_resp?.status_code !== 0 || !data.data?.audio) {
          const errMsg = data.base_resp?.status_msg || JSON.stringify(data).substring(0, 300);
          throw new HttpError(500, `MiniMax Direct failed: ${errMsg}`);
        }

        // Convert hex → bytes → upload to R2
        const audioHex = data.data.audio;
        const bytes = new Uint8Array(audioHex.length / 2);
        for (let i = 0; i < audioHex.length; i += 2) {
          bytes[i / 2] = parseInt(audioHex.substr(i, 2), 16);
        }

        const fileName = `voiceover/${project_id}_${Date.now()}.mp3`;
        const voiceoverUrl = await uploadToR2(ctx, bytes, fileName);
        console.log(`✅ MiniMax sync done: ${(bytes.length / 1024).toFixed(0)} KB → ${voiceoverUrl}`);

        await saveSettings(ctx, settings, project_id, {
          project_id, selected_voice_id: selectedVoiceId,
          voiceover_status: 'completed', voiceover_url: voiceoverUrl,
          generation_task_id: '', voiceover_chunks: '',
          voiceover_total_chunks: 0, voiceover_completed_chunks: 0,
        });
        try { await ctx.db.Projects.update(project_id, { voiceover_url: voiceoverUrl }); } catch (e) {}

        return {
          success: true, provider: 'minimax_direct',
          voiceover_url: voiceoverUrl, word_count: wordCount,
          status: 'completed', instant: true,
        };

      } else {
        // ── PATH B: MiniMax Direct ASYNC (long scripts) ─────────
        console.log(`📍 Path B: MiniMax ASYNC — ${cleanedText.length} chars`);

        const response = await fetch('https://api.minimax.io/v1/t2a_async_v2', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${MINIMAX_KEY}`,
          },
          body: JSON.stringify({
            model: 'speech-2.8-hd',
            text: cleanedText,
            language_boost: 'auto',
            voice_setting: { voice_id: selectedVoiceId, speed: 1.0, vol: 1.0, pitch: 0 },
            audio_setting: { audio_sample_rate: 32000, bitrate: 128000, format: 'mp3', channel: 1 },
          }),
        });

        const data = await response.json();

        if (data.base_resp?.status_code !== 0 || !data.task_id) {
          const errMsg = data.base_resp?.status_msg || JSON.stringify(data).substring(0, 300);
          throw new HttpError(500, `MiniMax async failed: ${errMsg}`);
        }

        const taskId = data.task_id;
        console.log(`✅ MiniMax async task: ${taskId}`);

        // Prefix task_id so pollVoiceover knows which API to poll
        await saveSettings(ctx, settings, project_id, {
          project_id, selected_voice_id: selectedVoiceId,
          voiceover_status: 'generating', generation_task_id: `minimax:${taskId}`,
          voiceover_url: '', voiceover_chunks: '',
          voiceover_total_chunks: 0, voiceover_completed_chunks: 0,
        });

        return {
          success: true, provider: 'minimax_async',
          task_id: taskId, word_count: wordCount,
          status: 'generating', instant: false,
        };
      }
    }

    // ════════════════════════════════════════════════════════════
    // PATH C: AI33 PRO ASYNC (submit → pollVoiceover polls)
    // ════════════════════════════════════════════════════════════
    if (!AI33_KEY) {
      throw new HttpError(500, 'AI33_API_KEY not configured. Switch to MiniMax Direct.');
    }

    console.log(`📍 Path C: AI33 Async — ${cleanedText.length} chars`);

    const supportedPrefixes = ['elevenlabs_', 'minimax_', 'clone_', 'edge_', 'kokoro_', 'vbee_', 'fishaudio_'];
    let v3VoiceId = selectedVoiceId;
    if (!supportedPrefixes.some(prefix => v3VoiceId.startsWith(prefix))) {
      if (voice_category === 'elevenlabs' || voice_category === 'elevenlabs_library') {
        v3VoiceId = `elevenlabs_${v3VoiceId}`;
      } else if (voice_category === 'cloned' || voice_category === 'minimax_cloned') {
        v3VoiceId = `clone_${v3VoiceId}`;
      } else {
        v3VoiceId = `minimax_${v3VoiceId}`;
      }
    }

    const submitBody = new FormData();
    submitBody.append('text', cleanedText);
    submitBody.append('voice_id', v3VoiceId);
    submitBody.append('speed', '1');
    submitBody.append('with_transcript', 'false');

    const submitRes = await fetch('https://api.ai33.pro/v3/text-to-speech', {
      method: 'POST',
      headers: { 'xi-api-key': AI33_KEY },
      body: submitBody,
    });

    const submitData = await submitRes.json();

    if (!submitData.success || !submitData.task_id) {
      const errMsg = JSON.stringify(submitData).substring(0, 300);
      throw new HttpError(500, `AI33 submit failed: ${errMsg}`);
    }

    const taskId = submitData.task_id;
    console.log(`✅ AI33 task: ${taskId}`);

    // Prefix with ai33: so pollVoiceover knows which API to poll
    await saveSettings(ctx, settings, project_id, {
      project_id, selected_voice_id: selectedVoiceId,
      voiceover_status: 'generating', generation_task_id: `ai33:${taskId}`,
      voiceover_url: '', voiceover_chunks: '',
      voiceover_total_chunks: 0, voiceover_completed_chunks: 0,
    });

    return {
      success: true, provider: 'ai33_async',
      task_id: taskId, word_count: wordCount,
      char_count: cleanedText.length,
      status: 'generating', instant: false,
    };

  } catch (error) {
    console.error(`❌ generateVoiceover error: ${error.message}`);
    throw error instanceof HttpError ? error : new HttpError(500, error.message);
  }
};

export default handler;
