// Ported from the original hosted generateSceneVideo function
// @ts-nocheck — temporary Phase 7 port debt; runtime behavior is preserved verbatim.
// Generated by migration/tools/port-fn.mjs; Phase 7 port review completed.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import type { FnHandler } from '../types';

// ══════════════════════════════════════════════════════════════════
// SCENE VIDEO GENERATOR — Seedance 1.5 Pro image-to-video via Kie API
// ══════════════════════════════════════════════════════════════════
// Generates an animated clip from the scene's still image.
// 480p, 10s, no audio — $0.0875 per clip, the same price as 720p at 5s but twice the motion.
// Played at 0.8x on the timeline a clip fills 12.5s and stays smooth (24fps source ->
// ~19 new frames a second). Model from the 2026-09-15 bake-off; 480p/10s chosen by the
// owner for runtime per dollar.
//
// REQUIRES: Scene must have a public HTTP image_url.
// ══════════════════════════════════════════════════════════════════

const KIE_BASE = "https://api.kie.ai/api/v1/jobs";

const SEEDANCE_MODEL = "bytedance/seedance-1.5-pro";

// The breakdown stores a bare camera word ("push_in") as the animation prompt. A video
// model reads that literally, so give it a sentence instead.
const CAMERA_PHRASES = {
  push_in: "slow cinematic push-in",
  zoom_in: "slow cinematic push-in",
  slow_zoom_in: "slow cinematic push-in",
  zoom_out: "slow cinematic pull-back",
  slow_zoom_out: "slow cinematic pull-back",
  pan_left: "slow pan to the left",
  pan_right: "slow pan to the right",
  slow_pan: "slow horizontal pan",
  static: "locked-off camera",
};

// Image-to-video models animate a still by inventing movement, and the classic failure is
// a figure caught mid-stride: the model slides the body across the ground while the feet
// stay planted the other way, so the subject appears to walk backwards. Saying what may
// move — and that nobody travels across the frame — removes the guesswork.
const MOTION_CONTRACT =
  'Motion rules: the CAMERA moves as described; the people and objects stay where they are ' +
  'and do not travel across the frame. Feet keep firm contact with the ground and never ' +
  'slide, skate, glide or step backwards; if a figure is caught mid-stride, the stride ' +
  'continues naturally in the exact direction the feet, knees and hips already point, and ' +
  'the body turns with it. Anatomy stays consistent: no limbs detaching, stretching, ' +
  'swapping or bending the wrong way, no extra fingers, no morphing heads or faces. ' +
  'Nothing new enters the frame — no new people, objects or text. Movement is limited to ' +
  'breathing, small weight shifts, hands and head turning slightly, hair and cloth ' +
  'settling, flame, smoke, dust, rain, water and shifting light.';

// Seedance takes a single prompt string; keep the description from crowding out the rules.
const MAX_PROMPT_CHARS = 1800;

function animationPrompt(raw) {
  const text = (raw || "").trim();
  let described;
  if (!text) {
    described = "Subtle cinematic motion, slow camera movement";
  } else if (/^[a-z_]+$/.test(text)) {
    described = `${CAMERA_PHRASES[text] || text.replace(/_/g, " ")}, subtle natural motion in the scene`;
  } else {
    described = text;
  }

  const room = MAX_PROMPT_CHARS - MOTION_CONTRACT.length - 2;
  if (described.length > room) described = `${described.slice(0, Math.max(0, room - 1))}…`;
  return `${described}. ${MOTION_CONTRACT}`;
}

const handler: FnHandler = async (body, ctx) => {
  let scene_id;

  try {
    scene_id = body.scene_id;

    const KIE_API_KEY = await ctx.keys.get('KIE_API_KEY');
    if (!KIE_API_KEY) throw new HttpError(500, 'KIE_API_KEY not configured');

    const scenes = await ctx.db.Scenes.filter({ id: scene_id });
    const scene = scenes[0];
    if (!scene) throw new HttpError(404, 'Scene not found');

    if (!scene.image_url) {
      throw new HttpError(400, 'Scene image must be generated first');
    }

    if (scene.image_url.startsWith('data:')) {
      throw new HttpError(400, 'Scene image is a data URI. Requires a public URL. Re-generate the scene image.');
    }

    if (!scene.image_url.startsWith('http')) {
      throw new HttpError(400, 'Scene image must be a public HTTP URL');
    }

    const projects = await ctx.db.Projects.filter({ id: scene.project_id });
    const aspectRatio = projects[0]?.orientation === 'portrait' ? '9:16' : '16:9';

    const prompt = animationPrompt(scene.animation_prompt);

    console.log(`🎬 Scene ${scene.scene_number} | Seedance 1.5 Pro image-to-video | 480p 10s`);
    console.log(`🖼️ Image: ${scene.image_url.substring(0, 80)}...`);
    console.log(`🎥 Prompt: ${prompt.substring(0, 120)}...`);

    // ══════════════════════════════════════════════════════════════
    // SUBMIT TO SEEDANCE 1.5 PRO VIA KIE
    // ══════════════════════════════════════════════════════════════

    const response = await fetch(`${KIE_BASE}/createTask`, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${KIE_API_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: SEEDANCE_MODEL,
        input: {
          prompt,
          input_urls: [scene.image_url],
          resolution: "480p",
          duration: "10",
          aspect_ratio: aspectRatio,
          generate_audio: false,
          fixed_lens: false
        }
      })
    });

    const resText = await response.text();
    console.log(`Kie response (${response.status}): ${resText.substring(0, 300)}`);

    let resData;
    try {
      resData = JSON.parse(resText);
    } catch (e) {
      throw new Error("Kie returned non-JSON: " + resText.substring(0, 200));
    }

    if (!response.ok || resData.code !== 200) {
      throw new Error(`Kie API error: ${resData.message || resData.msg || resText.substring(0, 200)}`);
    }

    const taskId = resData.data?.taskId;
    if (!taskId) throw new Error("No taskId returned from Kie API");

    console.log(`✓ Seedance video task created: ${taskId}`);

    // pollSceneVideo resolves any KIE task; the prefix records which model made it
    await ctx.db.Scenes.update(scene_id, {
      video_url: `seedance_task:${taskId}`,
      status: "pending"
    });

    return {
      success: true,
      task_id: taskId,
      scene_number: scene.scene_number,
      provider: SEEDANCE_MODEL,
      status: "CREATED"
    };

  } catch (error) {
    console.error("generateSceneVideo error:", error.message, error.stack);
    // A rejected request (no image yet, wrong URL shape) is not a failed scene. Marking
    // it 'failed' took the scene out of image polling AND out of every bulk action, so a
    // paid image was never collected and the scene could only be fixed one at a time.
    const isRequestError = error instanceof HttpError && error.status >= 400 && error.status < 500;
    if (scene_id && !isRequestError) {
      try {
        await ctx.db.Scenes.update(scene_id, { status: "failed" });
      } catch (_) {}
    }
    throw error instanceof HttpError ? error : new HttpError(500, error.message);
  }
};

export default handler;
