// Ported from the original hosted generateThumbnailImage function
// @ts-nocheck — temporary Phase 7 port debt; runtime behavior is preserved verbatim.
// Generated by migration/tools/port-fn.mjs; Phase 7 port review completed.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import type { FnHandler } from '../types';


// ══════════════════════════════════════════════════════════════════
// THUMBNAIL IMAGE GENERATION
// Primary: KIE SeedDream 4.5 (async submit → poll via pollThumbnailTask)
// Fallback: Ideogram V3 via KIE (sync poll in-function)
// ══════════════════════════════════════════════════════════════════

const KIE_BASE = "https://api.kie.ai/api/v1/jobs";

// ── KIE helpers (for Ideogram fallback) ─────────────────────────

async function kieCreate(apiKey, model, input) {
  const r = await fetch(KIE_BASE + "/createTask", {
    method: "POST",
    headers: { Authorization: "Bearer " + apiKey, "Content-Type": "application/json" },
    body: JSON.stringify({ model, input })
  });
  const d = await r.json();
  if (!r.ok || d.code !== 200) throw new Error("Kie " + model + ": " + (d.msg || JSON.stringify(d)));
  return d.data.taskId;
}

async function kiePoll(apiKey, taskId) {
  const start = Date.now();
  while (Date.now() - start < 120000) {
    await new Promise(r => setTimeout(r, 4000));
    const r = await fetch(KIE_BASE + "/recordInfo?taskId=" + taskId, { headers: { Authorization: "Bearer " + apiKey } });
    const d = await r.json();
    if (d.code !== 200) continue;
    if (d.data?.state === "success") {
      const j = JSON.parse(d.data.resultJson || "{}");
      return j.resultUrls?.[0] || j.url || j.imageUrl || null;
    }
    if (d.data?.state === "fail") throw new Error(d.data?.failMsg || "failed");
  }
  throw new Error("timeout");
}

// ── Prompt prep for thumbnail ───────────────────────────────────

function prepareThumbnailPrompt(rawPrompt) {
  let p = rawPrompt;
  // Strip resolution numbers (models render them as text)
  p = p
    .replace(/\b\d{3,4}\s*[x×]\s*\d{3,4}\s*(pixels?|px)?\b/gi, '')
    .replace(/\b(8K|4K|1080p|720p)\s*(resolution|quality|detail)?\b/gi, 'highly detailed');
  // Strip f-stop numbers
  p = p.replace(/\bf[/:]?\s*\d+\.?\d*\b/gi, 'shallow depth of field');
  // Markdown artifacts
  p = p.replace(/\*\*([^*]+)\*\*/g, '$1').replace(/\*/g, '').replace(/#{1,3}\s*/g, '');
  // Clean punctuation
  p = p.replace(/,\s*,/g, ',').replace(/\.\s*\./g, '.').replace(/\s{2,}/g, ' ').trim();
  return p;
}

// ══════════════════════════════════════════════════════════════════
// MAIN HANDLER
// ══════════════════════════════════════════════════════════════════

const handler: FnHandler = async (body, ctx) => {
  try {
    const user = ctx.user;

    const KIE_KEY = await ctx.keys.get('KIE_API_KEY');
    if (!KIE_KEY) throw new HttpError(500, 'No image API keys configured');

    const { concept_id } = body;
    if (!concept_id) throw new HttpError(400, 'concept_id required');

    const concepts = await ctx.db.ThumbnailConcepts.filter({ id: concept_id });
    const concept = concepts[0];
    if (!concept) throw new HttpError(404, 'Concept not found');

    const prompt = concept.image_prompt;
    if (!prompt) throw new HttpError(400, 'No image prompt on concept');

    // Detect shorts from prompt content
    const isShorts = prompt.includes('9:16') || prompt.includes('1080x1920');
    const aspectRatio = isShorts ? "9:16" : "16:9";
    const imageSize = isShorts ? "portrait_9_16" : "landscape_16_9";

    const cleanPrompt = prepareThumbnailPrompt(prompt);

    console.log(`🖼️ Generating thumbnail for concept ${concept_id} (${cleanPrompt.length} chars)`);

    // ═══════════════════════════════════════════════════════════
    // PRIMARY: KIE SeedDream (async submit → frontend polls)
    // ═══════════════════════════════════════════════════════════
    try {
      const seedreamPrompt = cleanPrompt + ". Ultra high resolution, crisp sharp details, professional YouTube thumbnail quality, cinematic lighting.";
      const taskId = await kieCreate(KIE_KEY, 'seedream-4.5', {
        prompt: seedreamPrompt.substring(0, 4000),
        aspect_ratio: aspectRatio,
        resolution: '2K',
      });

      return {
        success: false,
        pending: true,
        task_id: taskId,
        task_type: 'kie',
        concept_id,
        model: 'seedream-4.5',
      };
    } catch (error) {
      console.warn('KIE Seedream submit failed:', error.message, '→ falling back to Ideogram');
    }

    // ═══════════════════════════════════════════════════════════
    // FALLBACK: Ideogram V3 via KIE (sync poll in-function)
    // ═══════════════════════════════════════════════════════════
    let url = null;
    let model = 'none';

    // Try Ideogram V3 Quality
    try {
      const tid = await kieCreate(KIE_KEY, "ideogram/v3-text-to-image", {
        prompt: cleanPrompt.substring(0, 2000) + ". Ultra high resolution, crisp sharp details, professional quality.",
        image_size: imageSize, style: "DESIGN", rendering_speed: "QUALITY",
        expand_prompt: false,
        negative_prompt: "no text, no words, no letters, no numbers, no typography, no titles, no labels, no captions, no watermark, no signature, " + (concept.negative_prompt || "blurry, low quality, pixelated, distorted")
      });
      url = await kiePoll(KIE_KEY, tid);
      if (url) model = "ideogram-v3-quality";
    } catch (e) { console.warn("ideogram-v3 failed:", e.message); }

    // Fallback: Ideogram V3 Balanced
    if (!url) {
      try {
        const tid = await kieCreate(KIE_KEY, "ideogram/v3-text-to-image", {
          prompt: cleanPrompt.substring(0, 1200),
          image_size: imageSize, style: "DESIGN", rendering_speed: "BALANCED",
          expand_prompt: false,
          negative_prompt: "blurry, low quality, pixelated, watermark"
        });
        url = await kiePoll(KIE_KEY, tid);
        if (url) model = "ideogram-v3-balanced";
      } catch (e) { console.warn("ideogram-balanced failed:", e.message); }
    }

    // Fallback: Grok Imagine
    if (!url) {
      try {
        const tid = await kieCreate(KIE_KEY, "grok-imagine/text-to-image", {
          prompt: cleanPrompt.substring(0, 1500), aspect_ratio: aspectRatio
        });
        url = await kiePoll(KIE_KEY, tid);
        if (url) model = "grok-imagine";
      } catch (e) { console.warn("grok-imagine failed:", e.message); }
    }

    if (url) {
      await ctx.db.ThumbnailConcepts.update(concept_id, { image_url: url });
      console.log(`✓ Thumbnail generated: ${model} — ${url.substring(0, 60)}`);
    }

    return {
      success: !!url,
      image_url: url,
      model,
      concept_id,
    };

  } catch (error) {
    console.error("generateThumbnailImage error:", error.message);
    throw error instanceof HttpError ? error : new HttpError(500, error.message);
  }
};

export default handler;
