// @ts-nocheck — legacy port; runtime contracts are covered by Phase 8 tests.
// Ported from base44/functions/generateMusic.ts
// Generated by migration/tools/port-fn.mjs; Phase 8 manual follow-ups resolved.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import { geminiFetch } from '../lib/ai';
import { submitMusic } from '../lib/ai33';
import type { FnHandler } from '../types';


// ══════════════════════════════════════════════════════════════════
// INTELLIGENT MUSIC GENERATION — Script-Aware Soundtrack
// ══════════════════════════════════════════════════════════════════

async function analyzeScriptForMusic(ctx, script, niche, tone) {
  
  const prompt = `You are an expert film music supervisor. Analyze this video script and determine the PERFECT background instrumental music.

SCRIPT:
"""
${script.substring(0, 3000)}
"""

NICHE: ${niche || 'general'}
TONE: ${tone || 'not specified'}

Analyze the script's emotional arc, pacing, subject matter, and energy level. Then recommend music that:
- Matches the STORY MOOD (not just the genre)
- Supports narration without competing with it
- Has the right energy arc (builds, sustains, or resolves)
- Fits the content type (documentary, motivational, thriller, educational, etc.)

MUSIC STYLE VOCABULARY (pick the most fitting combination):
- Genres: Cinematic, Epic Orchestral, Lo-Fi, Ambient, Electronic, Piano Ballad, Corporate, Hip-Hop Instrumental, Jazz, Acoustic Folk, Dark Ambient, Synthwave, Classical, World Music, Trap Beat, Indie
- Moods: Tense, Hopeful, Mysterious, Triumphant, Melancholic, Urgent, Peaceful, Suspenseful, Inspiring, Dark, Playful, Nostalgic, Dramatic, Reflective, Energetic, Somber
- Pacing: Slow build, Steady pulse, Fast-paced, Breathing/dynamic, Minimal ambient, Driving rhythm
- Instruments: Piano, Strings, Synth pads, Acoustic guitar, Orchestra, Bass-heavy, Percussion-driven, Ambient textures, Brass, Electronic beats

Return ONLY this JSON:
{
  "style": "2-3 word Suno style tag (e.g. 'Epic Cinematic Orchestral', 'Dark Ambient Electronic', 'Inspiring Piano Strings')",
  "music_prompt": "A rich 1-2 sentence prompt describing the exact sound (e.g. 'Slow-building orchestral score with deep cello undertones, rising strings, and subtle percussion that builds tension before resolving into a triumphant brass-led climax')",
  "title": "Short evocative track name under 80 chars",
  "reasoning": "Why this music fits this specific script"
}`; 

  try {
    const response = await geminiFetch(ctx, '/v1beta/models/gemini-2.0-flash:generateContent', {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: { temperature: 0.7, maxOutputTokens: 1024, responseMimeType: "application/json" }
        })
      });

    if (!response.ok) throw new Error(`Gemini ${response.status}`);
    const data = await response.json();
    const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!text) throw new Error("No Gemini response");
    return JSON.parse(text);
  } catch (err) {
    console.warn(`Music analysis failed: ${err.message} — using fallback`);
    return null;
  }
}

const handler: FnHandler = async (body, ctx) => {
  try {
    const user = ctx.user;

    const { track_id, prompt, genre, mood, project_id } = body;

    if (track_id) {
      await ctx.db.MusicTracks.update(track_id, { status: 'generating' });
    }

    // ══════════════════════════════════════════════════════════════
    // STEP 1: Try to analyze the actual script for intelligent music selection
    // ══════════════════════════════════════════════════════════════
    let musicPrompt, style, title;
    let analysisUsed = false;

    let isSleepProject = false;

    if (project_id) {
      try {
        const projects = await ctx.db.Projects.filter({ id: project_id });
        const project = projects[0];

        if (project) {
          isSleepProject = project.project_mode === 'sleep_meditation' || project.project_mode === 'sleep_story';
        }

        if (project?.script) {
          console.log(`🎵 Analyzing script for intelligent music selection...`);
          const analysis = await analyzeScriptForMusic(ctx, 
            project.script,
            project.niche,
            project.tone
          );

          if (analysis) {
            musicPrompt = analysis.music_prompt;
            style = analysis.style;
            title = analysis.title;
            analysisUsed = true;
            console.log(`🎵 Music analysis: style="${style}" | ${analysis.reasoning}`);
          }
        }
      } catch (err) {
        console.warn(`Script fetch failed: ${err.message} — using manual inputs`);
      }
    }

    // ══════════════════════════════════════════════════════════════
    // STEP 2: Fall back to manual inputs if no script analysis
    // ══════════════════════════════════════════════════════════════
    if (!analysisUsed) {
      musicPrompt = prompt || 'Cinematic background music for storytelling narration';
      style = genre || mood || 'Cinematic';
      title = (prompt || 'Background Track').substring(0, 80);
    }

    // Override with dedicated sleep music style for sleep projects
    if (isSleepProject) {
      musicPrompt = 'Deep ambient sleep music, 432Hz healing frequency, consistent low-end drone, warm synthesizer pads, minimal variation, extremely slow tempo, no percussion, no melodies, seamless loop, spatially immersive, dark calming atmosphere.';
      style = 'Dark Ambient Sleep';
      if (!title.toLowerCase().includes('sleep')) {
        title = 'Deep Sleep Ambient — ' + title.substring(0, 55);
      }
      analysisUsed = false; // Force override regardless of script analysis
      console.log(`🌙 Sleep mode: Dedicated sleep music style applied (432Hz + Delta wave)`);
    }

    // Enforce prompt length limit
    if (musicPrompt.length > 400) musicPrompt = musicPrompt.substring(0, 397) + '...';
    if (title.length > 80) title = title.substring(0, 80);

    // Kept byte-for-byte from the former KIE custom-mode request for prompt-audit
    // traceability. AI33 simple instrumental mode does not accept negative tags.
    const negativeTags = 'Vocals, Singing, Rap, Voice, Spoken Word, Choir, Humming, Whistling';
    void negativeTags;

    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
    console.log(`🎵 Music Generation | ${analysisUsed ? 'Script-Analyzed' : 'Manual Input'}`);
    console.log(`🎨 Style: ${style}`);
    console.log(`📝 Prompt: ${musicPrompt}`);
    console.log(`🎹 Title: ${title}`);
    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);

    const taskId = await submitMusic(ctx, musicPrompt);
    return {
      success: true,
      status: 'pending',
      task_id: taskId,
      music_style: style,
      music_prompt: musicPrompt,
      title,
      analysis_used: analysisUsed,
    };

  } catch (error) {
    console.error('generateMusic error:', error.message);
    if (body?.track_id) {
      try { await ctx.db.MusicTracks.update(body.track_id, { status: 'failed' }); } catch (_) {}
    }
    throw new HttpError(500, error.message);
  }
};

export default handler;
