// @ts-nocheck — legacy port; runtime contracts are covered by Phase 8 tests.
// Ported from the original hosted listVoices function
// Generated by migration/tools/port-fn.mjs; Phase 8 manual follow-ups resolved.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import type { FnHandler } from '../types';


// ══════════════════════════════════════════════════════════════════
// LIST VOICES — All via AI33 proxy (with 5-minute in-memory cache)
// ElevenLabs voices: /v2/voices + /v1/shared-voices
// MiniMax voices: /v1m/voice/list (standard) + /v1m/voice/clone (cloned)
// ══════════════════════════════════════════════════════════════════

// In-memory cache — survives across requests on the same Deno isolate
// Per user: voice libraries come from each user's own AI33 key and include their cloned
// voices. A single shared cache meant a warm isolate could serve one user's voices —
// clones included — to the next user for up to five minutes.
const voiceCache = new Map(); // userId -> { voices, at }
const inflightByUser = new Map(); // userId -> Promise
const CACHE_TTL = 5 * 60 * 1000; // 5 min

async function fetchAllVoices(ctx) {
  const AI33_KEY = await ctx.keys.get('AI33_API_KEY');
  const headers = { 'Content-Type': 'application/json', 'xi-api-key': AI33_KEY };
  const allVoices = [];

  // ── ELEVENLABS VOICES via AI33 ─────────────────────────────────
  try {
    const [recRes, libRes] = await Promise.all([
      fetch('https://api.ai33.pro/v2/voices', { headers }),
      fetch('https://api.ai33.pro/v1/shared-voices?page_size=50&sort=usage_character_count_7d&page=0', { headers }),
    ]);

    if (recRes.ok) {
      const data = await recRes.json();
      const voices = data.voices || data || [];
      for (const v of voices) {
        allVoices.push({
          voice_id: v.voice_id, name: v.name,
          description: (v.description || '').substring(0, 100),
          preview_url: v.preview_url, labels: v.labels || {},
          category: 'elevenlabs', provider: 'elevenlabs',
        });
      }
      console.log(`✓ ElevenLabs recommended: ${voices.length}`);
    }

    if (libRes.ok) {
      const data = await libRes.json();
      const voices = data.voices || [];
      for (const v of voices) {
        allVoices.push({
          voice_id: v.voice_id, name: v.name,
          description: (v.description || '').substring(0, 100),
          preview_url: v.preview_url,
          labels: { accent: v.accent, gender: v.gender, age: v.age, use_case: v.use_case },
          category: 'elevenlabs_library', provider: 'elevenlabs',
        });
      }
      console.log(`✓ ElevenLabs library: ${voices.length}`);
    }
  } catch (e) {
    console.warn('ElevenLabs voice list error:', e.message);
  }

  // ── MINIMAX VOICES via AI33 ────────────────────────────────────
  try {
    const [mmRes, cloneRes] = await Promise.all([
      fetch('https://api.ai33.pro/v1m/voice/list', {
        method: 'POST', headers,
        body: JSON.stringify({ page: 1, page_size: 100, tag_list: [] }),
      }),
      fetch('https://api.ai33.pro/v1m/voice/clone', { headers }),
    ]);

    if (mmRes.ok) {
      const data = await mmRes.json();
      const voices = data.data?.voice_list || [];
      for (const v of voices) {
        allVoices.push({
          voice_id: v.voice_id, name: v.voice_name || v.voice_id,
          description: (v.tag_list || []).join(', '),
          preview_url: v.sample_audio || null,
          labels: {
            accent: (v.tag_list || []).find(t => t.includes('EN-') || t === 'English') || '',
            gender: (v.tag_list || []).find(t => t === 'Male' || t === 'Female')?.toLowerCase() || '',
            age: (v.tag_list || []).find(t => t.includes('Age') || t === 'Young' || t === 'Middle Age') || '',
            use_case: 'narration',
          },
          category: 'minimax', provider: 'minimax',
        });
      }
      console.log(`✓ MiniMax standard: ${voices.length}`);
    }

    if (cloneRes.ok) {
      const data = await cloneRes.json();
      const voices = data.data || [];
      for (const v of voices) {
        allVoices.push({
          voice_id: v.voice_id, name: v.voice_name || v.voice_id,
          description: 'Cloned voice', preview_url: v.sample_audio || null,
          labels: { accent: '', gender: '', age: '', use_case: 'cloned' },
          category: 'minimax_cloned', provider: 'minimax',
        });
      }
      console.log(`✓ MiniMax cloned: ${voices.length}`);
    }
  } catch (e) {
    console.warn('MiniMax voice list error:', e.message);
  }

  // Deduplicate
  const seen = new Set();
  const unique = allVoices.filter(v => {
    if (seen.has(v.voice_id)) return false;
    seen.add(v.voice_id);
    return true;
  });

  console.log(`VOICE_TOTAL: ${unique.length}`);
  return unique;
}

const handler: FnHandler = async (body, ctx) => {
  try {
    const user = ctx.user;

    const AI33_KEY = await ctx.keys.get('AI33_API_KEY');
    if (!AI33_KEY) {
      throw new HttpError(500, 'AI33_API_KEY not configured');
    }

    // Return cached result if fresh
    const cached = voiceCache.get(user.id);
    if (cached && (Date.now() - cached.at) < CACHE_TTL) {
      console.log(`✓ Serving ${cached.voices.length} voices from cache`);
      return { success: true, voices: cached.voices, total: cached.voices.length };
    }

    // Dedup concurrent in-flight requests — per user, since each fetch uses that user's
    // own key. Sharing one promise handed user A's voices to user B.
    if (!inflightByUser.has(user.id)) {
      inflightByUser.set(user.id, fetchAllVoices(ctx).then(result => {
        // An empty list is a failure, not an answer: caching it meant the voice panel
        // stayed empty for five minutes after the provider recovered.
        if (result.length > 0) voiceCache.set(user.id, { voices: result, at: Date.now() });
        inflightByUser.delete(user.id);
        return result;
      }).catch(err => {
        inflightByUser.delete(user.id);
        throw err;
      }));
    }

    const unique = await inflightByUser.get(user.id);

    return { success: true, voices: unique, total: unique.length };
  } catch (error) {
    throw error instanceof HttpError ? error : new HttpError(500, error.message);
  }
};

export default handler;
