// Ported from the original hosted pollSceneImage function
// @ts-nocheck — temporary Phase 7 port debt; runtime behavior is preserved verbatim.
// Generated by migration/tools/port-fn.mjs; Phase 7 port review completed.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import { createImageTask, recordInfo } from '../lib/kie';
import { ingestUrl } from '../lib/storage';
import type { Ctx, FnHandler } from '../types';

// ══════════════════════════════════════════════════════════════════
// POLL SCENE IMAGE — checks KIE tasks, persists results, and advances
// through the Nano Banana 2 Lite → Grok → Nano fallback chain.
// ══════════════════════════════════════════════════════════════════

const prefixes = {
  seedream: 'seedream_task:',
  grok: 'grok_img_task:',
  nano: 'nano_task:',
  nb2lite: 'nb2lite_task:',
} as const;

type Provider = keyof typeof prefixes;

function cleanPrompt(scene: any, maxChars: number) {
  let prompt = (scene.image_prompt || '').substring(0, maxChars);
  if (prompt.startsWith('DIRECTOR_NOTES:')) return null;
  return prompt
    .replace(/\b(8K|4K|1080p)\s*(resolution|quality|detail)?\b/gi, 'highly detailed')
    .replace(/\b\d{3,4}\s*[x×]\s*\d{3,4}\b/gi, '')
    .replace(/\bf[/:]?\s*\d+\.?\d*\b/gi, 'shallow depth of field');
}

function detectCharacterInScene(scene: any) {
  if (scene.image_prompt?.startsWith('DIRECTOR_NOTES:')) {
    try {
      const notes = JSON.parse(scene.image_prompt.substring('DIRECTOR_NOTES:'.length));
      if (notes.characters_present?.length > 0) return true;
    } catch (_) {}
  }
  const prompt = (scene.image_prompt || '').toLowerCase();
  return /\b(woman|man|person|figure|character|boy|girl|child|worker|doctor|soldier|officer|teacher|scientist|skeleton|mannequin|people|crowd|couple|family|mother|father|husband|wife|protagonist|narrator)\b/.test(prompt);
}

async function submitProvider(
  ctx: Ctx,
  provider: Provider,
  scene: any,
  aspectRatio: string,
  referenceImageUrl?: string | null,
) {
  const prompt = cleanPrompt(scene, provider === 'seedream' || provider === 'nb2lite' ? 4000 : 1500);
  if (!prompt) return null;

  if (provider === 'seedream') {
    return createImageTask(ctx, 'seedream-4.5', {
      prompt,
      aspect_ratio: aspectRatio,
      resolution: '2K',
    });
  }

  if (provider === 'nb2lite') {
    const useReference = detectCharacterInScene(scene)
      && referenceImageUrl
      && referenceImageUrl.startsWith('http');
    return createImageTask(ctx, 'nano-banana-2-lite', {
      prompt,
      aspect_ratio: aspectRatio,
      ...(useReference ? { image_urls: [referenceImageUrl] } : {}),
    });
  }

  if (provider === 'grok') {
    const useReference = detectCharacterInScene(scene)
      && referenceImageUrl
      && referenceImageUrl.startsWith('http');
    return createImageTask(
      ctx,
      useReference ? 'grok-imagine/image-to-image' : 'grok-imagine/text-to-image',
      useReference
        ? { prompt, image_urls: [referenceImageUrl] }
        : { prompt, aspect_ratio: aspectRatio },
    );
  }

  return createImageTask(ctx, 'google/nano-banana', {
    prompt,
    output_format: 'png',
    image_size: aspectRatio,
  });
}

async function moveToProvider(
  ctx: Ctx,
  provider: Provider,
  scene: any,
  project: any,
  fallback: string,
) {
  try {
    const aspectRatio = project?.orientation === 'portrait' ? '9:16' : '16:9';
    const taskId = await submitProvider(ctx, provider, scene, aspectRatio, project?.reference_image_url);
    if (!taskId) return null;
    await ctx.db.Scenes.update(scene.id, {
      image_url: `${prefixes[provider]}${taskId}`,
      status: 'image_pending',
    });
    return { scene_number: scene.scene_number, status: 'processing', fallback };
  } catch (error) {
    console.warn(`⚠️ Scene ${scene.scene_number}: ${provider} submit failed — ${error.message}`);
    return null;
  }
}

async function persistSceneResult(ctx: Ctx, scene: any, project: any, providerUrl: string) {
  const stored = await ingestUrl(ctx, providerUrl, { tier: 'durable', prefix: 'scenes' });
  await ctx.db.Scenes.update(scene.id, { image_url: stored.url, status: 'image_generated' });

  if (project && !project.reference_image_url && detectCharacterInScene(scene)) {
    try {
      await ctx.db.Projects.update(project.id, { reference_image_url: stored.url });
      project.reference_image_url = stored.url;
      console.log(`📌 Scene ${scene.scene_number} reference locked: ${stored.url.substring(0, 60)}`);
    } catch (error) {
      console.warn(`⚠️ Failed to lock reference: ${error.message}`);
    }
  }
  return stored.url;
}

function parseTask(imageUrl: string): { provider: Provider; taskId: string } | null {
  for (const [provider, prefix] of Object.entries(prefixes) as [Provider, string][]) {
    if (imageUrl.startsWith(prefix)) return { provider, taskId: imageUrl.slice(prefix.length) };
  }
  return null;
}

const handler: FnHandler = async (body, ctx) => {
  try {
    const { scene_id, project_id } = body;
    await ctx.keys.require('KIE_API_KEY');

    let scenesToPoll: any[] = [];
    let projectForRef: any = null;

    if (scene_id) {
      const scenes = await ctx.db.Scenes.filter({ id: scene_id });
      if (scenes[0]) {
        scenesToPoll = [scenes[0]];
        const projects = await ctx.db.Projects.filter({ id: scenes[0].project_id });
        projectForRef = projects[0];
      }
    } else if (project_id) {
      const all = await ctx.db.Scenes.filter({ project_id });
      scenesToPoll = all.filter((scene: any) => scene.status === 'image_pending');
      const projects = await ctx.db.Projects.filter({ id: project_id });
      projectForRef = projects[0];
    } else {
      throw new HttpError(400, 'Provide scene_id or project_id');
    }

    if (scenesToPoll.length === 0) {
      return { success: true, done: true, results: [], pending: 0, completed: 0, failed: 0 };
    }

    // A queued 2K or reference-image job can legitimately take several minutes. At four
    // minutes this declared such a job stale and resubmitted it to another provider —
    // orphaning the original result and paying for it twice.
    const staleThresholdMs = 12 * 60 * 1000;
    const now = Date.now();
    const results: any[] = [];

    for (const scene of scenesToPoll) {
      const imageUrl = scene.image_url || '';
      const sceneNum = scene.scene_number;

      try {
        if (imageUrl.startsWith('http')) {
          if (scene.status === 'image_pending') await ctx.db.Scenes.update(scene.id, { status: 'image_generated' });
          results.push({ scene_number: sceneNum, status: 'done', image_url: imageUrl });
          continue;
        }

        const task = parseTask(imageUrl);
        const updatedAt = scene.updated_date ? new Date(scene.updated_date).getTime() : 0;
        const stale = updatedAt > 0 && now - updatedAt > staleThresholdMs;

        if (!task || stale) {
          const recovered = await moveToProvider(ctx, 'nb2lite', scene, projectForRef, stale ? 'nb2lite_stale_recovery' : 'nb2lite_legacy_recovery')
            || await moveToProvider(ctx, 'grok', scene, projectForRef, 'grok_stale_recovery');
          if (recovered) results.push(recovered);
          else {
            await ctx.db.Scenes.update(scene.id, { status: 'image_failed', image_url: '' });
            results.push({ scene_number: sceneNum, status: 'failed', error: 'Stale task, all providers failed' });
          }
          continue;
        }

        const record = await recordInfo(ctx, task.taskId);
        if (record.state === 'processing') {
          results.push({ scene_number: sceneNum, status: 'processing', progress: record.raw?.progress || null });
          continue;
        }

        if (record.state === 'success' && record.url) {
          const storedUrl = await persistSceneResult(ctx, scene, projectForRef, record.url);
          console.log(`✅ Scene ${sceneNum}: ${task.provider} done → ${storedUrl.substring(0, 60)}`);
          results.push({ scene_number: sceneNum, status: 'done', image_url: storedUrl });
          continue;
        }

        const fallbackProvider: Provider | null = task.provider === 'seedream' || task.provider === 'nb2lite'
          ? 'grok'
          : task.provider === 'grok'
            ? 'nano'
            : null;
        const fallback = fallbackProvider
          ? await moveToProvider(ctx, fallbackProvider, scene, projectForRef, fallbackProvider)
          : null;
        if (fallback) results.push(fallback);
        else {
          const error = record.failMsg || `${task.provider} task failed`;
          await ctx.db.Scenes.update(scene.id, { status: 'image_failed', image_url: '' });
          results.push({ scene_number: sceneNum, status: 'failed', error });
        }
      } catch (error) {
        console.warn(`⚠️ Poll error scene ${sceneNum}: ${error.message}`);
        results.push({ scene_number: sceneNum, status: 'error', error: error.message });
      }
    }

    const pending = results.filter((result) => result.status === 'processing').length;
    const completed = results.filter((result) => result.status === 'done').length;
    const failed = results.filter((result) => result.status === 'failed').length;
    const errors = results.filter((result) => result.status === 'error').length;
    const pid = project_id || scenesToPoll[0]?.project_id;
    let allProjectPending = 0;

    if (pid) {
      const allScenes = await ctx.db.Scenes.filter({ project_id: pid });
      allProjectPending = allScenes.filter((scene: any) => scene.status === 'image_pending').length;
      if (allProjectPending === 0) {
        const stillNeedImages = allScenes.filter((scene: any) => scene.status === 'prompts_ready' || scene.status === 'image_failed').length;
        if (stillNeedImages === 0) {
          try {
            await ctx.db.Projects.update(pid, { status: 'images_complete' });
          } catch (_) {}
        }
      }
    }

    return {
      success: true,
      done: allProjectPending === 0,
      pending: allProjectPending,
      completed,
      failed,
      errors,
      results,
    };
  } catch (error) {
    console.error('❌ pollSceneImage error:', error.message);
    throw error instanceof HttpError ? error : new HttpError(500, error.message);
  }
};

export default handler;
