// Ported from the original hosted pollThumbnailBlend function
// @ts-nocheck — temporary Phase 7 port debt; runtime behavior is preserved verbatim.
// Generated by migration/tools/port-fn.mjs; Phase 7 port review completed.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import { recordInfo } from '../lib/kie';
import { ingestUrl } from '../lib/storage';
import type { FnHandler } from '../types';

// pollThumbnailBlend — polls KIE task status for thumbnailBlend results

const handler: FnHandler = async (body, ctx) => {
  try {
    const { task_id, concept_id } = body;
    if (!task_id) throw new HttpError(400, 'task_id is required');

    const record = await recordInfo(ctx, task_id);

    if (record.state === 'success') {
      if (!record.url) {
        return { completed: false, state: 'processing' };
      }

      const stored = await ingestUrl(ctx, record.url, {
        tier: 'durable',
        prefix: `thumbnails/${concept_id || 'blend'}`,
      });

      if (concept_id) {
        try {
          await ctx.db.ThumbnailConcepts.update(concept_id, { image_url: stored.url });
        } catch (_) {}
      }

      return { completed: true, image_url: stored.url, error: null };
    }

    if (record.state === 'fail') {
      return { completed: true, error: record.failMsg || 'Blend failed' };
    }

    return { completed: false, state: record.state, progress: record.raw?.progress || null };
  } catch (error) {
    console.error('pollThumbnailBlend error:', error.message);
    throw error instanceof HttpError ? error : new HttpError(500, error.message);
  }
};

export default handler;
