// Ported from the original hosted pollTranscription function
// Generated by migration/tools/port-fn.mjs — prompt strings remain unchanged.

import { HttpError } from '../lib/http';
import { poll as asrPoll } from '../lib/asr';
import type { FnHandler } from '../types';

// ══════════════════════════════════════════════════════════════════
// POLL TRANSCRIPTION — Check selected ASR backend, return normalized words
// ══════════════════════════════════════════════════════════════════

const handler: FnHandler = async (body, ctx) => {
  const { transcript_id } = body;
  if (!transcript_id) throw new HttpError(400, 'transcript_id required');

  const result = await asrPoll(ctx, transcript_id);
  if (result.status === 'completed') {
    const words = result.words || [];
    return {
      status: 'completed',
      words,
      word_count: words.length,
      confidence: words.length
        ? words.reduce((sum, word) => sum + (word.confidence || 0), 0) / words.length
        : 0,
      duration: result.duration,
    };
  }
  if (result.status === 'error') {
    return { status: 'error', error: result.error || 'Transcription failed' };
  }
  return { status: result.status };
};

export default handler;
