// Ported from the original hosted pollThumbnailTask function
// @ts-nocheck — temporary Phase 7 port debt; runtime behavior is preserved verbatim.
// Generated by migration/tools/port-fn.mjs; Phase 7 port review completed.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import { recordInfo } from '../lib/kie';
import { ingestUrl } from '../lib/storage';
import type { FnHandler } from '../types';

// ══════════════════════════════════════════════════════════════════
// POLL THUMBNAIL TASK
// KIE owns thumbnail generation. Persist successful provider results before
// writing them into ThumbnailConcepts so stored URLs do not expire.
// ══════════════════════════════════════════════════════════════════

const handler: FnHandler = async (body, ctx) => {
  try {
    const { task_id, concept_id, task_type } = body;
    if (!task_id) throw new HttpError(400, 'task_id required');

    // Tasks created by the retired visual provider cannot be polled through KIE.
    if (task_type && task_type !== 'kie') {
      return {
        success: false,
        completed: true,
        error: 'This thumbnail uses a retired provider. Generate it again.',
        fallback_needed: true,
      };
    }

    const record = await recordInfo(ctx, task_id);
    console.log(`KIE poll task ${task_id}: state="${record.state}"`);

    if (record.state === 'success') {
      if (!record.url) {
        return { success: true, completed: false, state: 'processing' };
      }

      const stored = await ingestUrl(ctx, record.url, {
        tier: 'durable',
        prefix: `thumbnails/${concept_id || 'poll'}`,
      });

      if (concept_id) {
        try {
          await ctx.db.ThumbnailConcepts.update(concept_id, {
            image_url: stored.url,
            status: 'complete',
            is_selected: true,
          });
          console.log('✅ Saved KIE thumbnail to concept');
        } catch (error) {
          console.warn('Save error:', error.message);
        }
      }

      return { success: true, completed: true, image_url: stored.url };
    }

    if (record.state === 'fail') {
      return {
        success: false,
        completed: true,
        error: record.failMsg || 'Generation failed',
      };
    }

    return { success: true, completed: false, state: record.state };
  } catch (error) {
    console.error('pollThumbnailTask error:', error.message);
    throw new HttpError(500, error.message);
  }
};

export default handler;
