// Ported from the original hosted pollSceneVideo function
// @ts-nocheck — temporary Phase 7 port debt; runtime behavior is preserved verbatim.
// Generated by migration/tools/port-fn.mjs; Phase 7 port review completed.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import { ingestUrl } from '../lib/storage';
import type { FnHandler } from '../types';


// ══════════════════════════════════════════════════════════════════
// SCENE VIDEO POLLER — Checks Grok Imagine video task via Kie API
// ══════════════════════════════════════════════════════════════════
//
// Called after generateSceneVideo to check if video is ready.
// Reads the grok_vid_task:{taskId} stored on scene.video_url.
//
// FLOW:
//   1. Extract taskId from scene.video_url
//   2. Poll /jobs/recordInfo → check state
//   3. On success → grab resultUrls[0]
//   4. Update scene with final video URL
//
// ENDPOINT:
//   GET https://api.kie.ai/api/v1/jobs/recordInfo?taskId={id}
// ══════════════════════════════════════════════════════════════════

const KIE_BASE = "https://api.kie.ai/api/v1/jobs";

const handler: FnHandler = async (body, ctx) => {
  try {
    const user = ctx.user;

    const { scene_id } = body;

    const scenes = await ctx.db.Scenes.filter({ id: scene_id });
    const scene = scenes[0];
    if (!scene) throw new HttpError(404, 'Scene not found');

    const KIE_API_KEY = await ctx.keys.get('KIE_API_KEY');
    if (!KIE_API_KEY) {
      throw new HttpError(500, 'KIE_API_KEY not configured');
    } 

    // ── Extract task ID ─────────────────────────────────────────────
    const videoUrl = scene.video_url || '';

    // Already a final URL
    if (videoUrl.startsWith('http')) {
      return { success: true, status: 'COMPLETED', video_url: videoUrl };
    }

    // Extract task ID from any provider prefix
    let taskId = null;
    const prefixes = ['runway_task:', 'hailuo_task:', 'grok_vid_task:', 'veo_task:'];
    for (const prefix of prefixes) {
      if (videoUrl.startsWith(prefix)) {
        taskId = videoUrl.replace(prefix, '');
        break;
      }
    }

    if (!taskId && videoUrl.startsWith('freepik_task:')) {
      throw new HttpError(400, 'This scene uses a legacy video provider. Re-generate the video.');
    }

    if (!taskId) {
      throw new HttpError(400, 'No video task found on this scene');
    }

    console.log(`🔍 Polling Grok video task: ${taskId} for scene ${scene.scene_number}`);

    // ══════════════════════════════════════════════════════════════
    // POLL TASK STATUS via /jobs/recordInfo
    // ══════════════════════════════════════════════════════════════

    const statusRes = await fetch(`${KIE_BASE}/recordInfo?taskId=${taskId}`, {
      headers: { "Authorization": `Bearer ${KIE_API_KEY}` }
    });

    if (!statusRes.ok) {
      const errText = await statusRes.text();
      throw new HttpError(500, `Kie status check failed: ${statusRes.status} - ${errText}`);
    }

    const statusData = await statusRes.json();

    if (statusData.code !== 200) {
      throw new HttpError(500, `Kie status error: ${statusData.msg || statusData.message}`);
    }

    const record = statusData.data;
    const state = record?.state;
    const failMsg = record?.failMsg;

    // ── Still processing ────────────────────────────────────────────
    if (!state || state === 'processing' || state === 'pending' || state === 'queued') {
      console.log(`⏳ Grok video task ${taskId}: ${state || 'processing'}`);
      return {
        success: true,
        status: 'PROCESSING',
        task_id: taskId,
        scene_number: scene.scene_number,
        created_at: record?.createTime
      };
    }

    // ── Failed ──────────────────────────────────────────────────────
    if (state === 'fail') {
      console.error(`❌ Grok video task ${taskId} failed: ${failMsg || record?.failCode}`);

      await ctx.db.Scenes.update(scene_id, {
        status: 'video_failed'
      });

      return {
        success: false,
        status: 'FAILED',
        error: failMsg || 'Video generation failed',
        task_id: taskId
      };
    }

    // ── Completed ───────────────────────────────────────────────────
    if (state === 'success') {
      let resultJson = {};
      try {
        resultJson = JSON.parse(record.resultJson || '{}');
      } catch (_) {}

      const finalUrl = resultJson.resultUrls?.[0] || resultJson.url || resultJson.video_url;

      if (!finalUrl) {
        console.warn(`⚠️ Task ${taskId} success but no URL in resultJson — retry next poll`);
        return {
          success: true,
          status: 'PROCESSING',
          message: 'Completed but URL not ready yet',
          task_id: taskId,
          scene_number: scene.scene_number
        };
      }

      const stored = await ingestUrl(ctx, finalUrl, { tier: 'durable', prefix: 'scenes' });

      await ctx.db.Scenes.update(scene_id, {
        video_url: stored.url,
        status: 'video_ready'
      });

      console.log(`✓ Scene ${scene.scene_number} video saved: ${stored.url.substring(0, 80)}...`);

      return {
        success: true,
        status: 'COMPLETED',
        video_url: stored.url,
        resolution: '480p',
        task_id: taskId,
        scene_number: scene.scene_number
      };
    }

    // ── Unknown state ───────────────────────────────────────────────
    return {
      success: true,
      status: 'UNKNOWN',
      task_id: taskId,
      raw_state: state
    };

  } catch (error) {
    console.error("pollSceneVideo error:", error.message);
    throw new HttpError(500, error.message);
  }
};

export default handler;
