// @ts-nocheck — legacy port; runtime contracts are covered by Phase 8 tests.
// Ported from the original hosted previewVoice function
// Generated by migration/tools/port-fn.mjs; Phase 8 manual follow-ups resolved.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import type { FnHandler } from '../types';

// v2 — redeployed
// Generate a short TTS preview for a voice — all via AI33 proxy

const POLL_INTERVAL_MS = 2000;
// A preview is one sentence. Twelve polls is ~25s, which stays inside the gateway
// timeout in front of this Worker; sixty seconds of waiting only produced a dead socket.
const MAX_POLLS = 12;

const handler: FnHandler = async (body, ctx) => {
  try {
    const user = ctx.user;

    const { voice_id, provider } = body;
    if (!voice_id) throw new HttpError(400, 'Missing voice_id');

    const AI33_KEY = await ctx.keys.get('AI33_API_KEY');
    if (!AI33_KEY) throw new HttpError(500, 'AI33_API_KEY not configured');

    const previewText = "In a world where stories shape reality, every voice carries the power to transform silence into something unforgettable.";
    const headers = { 'Content-Type': 'application/json', 'xi-api-key': AI33_KEY };



    // ── MiniMax Direct — sync TTS, instant preview ──────────────
    if (provider === 'minimax_direct') {
      const MINIMAX_KEY = await ctx.keys.get('MINIMAX_API_KEY');
      if (!MINIMAX_KEY) throw new HttpError(500, 'MINIMAX_API_KEY not configured');

      try {
        const res = await fetch('https://api.minimax.io/v1/t2a_v2', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${MINIMAX_KEY}`,
          },
          body: JSON.stringify({
            model: 'speech-2.8-hd',
            text: previewText,
            stream: false,
            voice_setting: { voice_id, speed: 1.0, vol: 1.0, pitch: 0 },
            audio_setting: { sample_rate: 32000, bitrate: 128000, format: 'mp3', channel: 1 },
            output_format: 'url',
          }),
        });

        const data = await res.json();

        if (data.base_resp?.status_code === 0) {
          const audioUrl = data.data?.audio_url || data.data?.audio;
          if (audioUrl) {
            return { success: true, preview_url: audioUrl, voice_id };
          }
        }

        // If url format didn't work, try hex format and upload
        const res2 = await fetch('https://api.minimax.io/v1/t2a_v2', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${MINIMAX_KEY}`,
          },
          body: JSON.stringify({
            model: 'speech-2.8-hd',
            text: previewText,
            stream: false,
            voice_setting: { voice_id, speed: 1.0, vol: 1.0, pitch: 0 },
            audio_setting: { sample_rate: 32000, bitrate: 128000, format: 'mp3', channel: 1 },
            output_format: 'hex',
          }),
        });

        const data2 = await res2.json();
        if (data2.base_resp?.status_code === 0 && data2.data?.audio) {
          const audioHex = data2.data.audio;
          const bytes = new Uint8Array(audioHex.length / 2);
          for (let i = 0; i < audioHex.length; i += 2) {
            bytes[i / 2] = parseInt(audioHex.substr(i, 2), 16);
          }
          // Spreading a whole MP3 into String.fromCharCode overflows the argument stack
          // on anything but a tiny clip, so encode in chunks.
          let binary = '';
          for (let i = 0; i < bytes.length; i += 8192) {
            binary += String.fromCharCode.apply(null, bytes.subarray(i, i + 8192));
          }
          return {
            success: true,
            preview_url: `data:audio/mpeg;base64,${btoa(binary)}`,
            voice_id,
          };
        }

        throw new Error(`MiniMax preview failed: ${data.base_resp?.status_msg || 'unknown'}`);
      } catch (err) {
        console.warn('MiniMax Direct preview failed, falling back to AI33:', err.message);
        // Fall through to AI33 path below
      }
    }

    // The voice ids the panel shows come from AI33's v3 library already prefixed
    // (elevenlabs_, minimax_, clone_). This used to post them to an ElevenLabs-shaped
    // endpoint that expects a bare id, so previews failed for every voice without a
    // provider-supplied sample. Use the same v3 endpoint the real voiceover uses.
    const supportedPrefixes = ['elevenlabs_', 'minimax_', 'clone_', 'edge_', 'kokoro_', 'vbee_', 'fishaudio_'];
    const v3VoiceId = supportedPrefixes.some(p => String(voice_id).startsWith(p))
      ? String(voice_id)
      : `${provider === 'minimax' ? 'minimax' : 'elevenlabs'}_${voice_id}`;

    const form = new FormData();
    form.append('text', previewText);
    form.append('voice_id', v3VoiceId);
    form.append('speed', '1');
    form.append('with_transcript', 'false');

    const submitRes = await fetch('https://api.ai33.pro/v3/text-to-speech', {
      method: 'POST',
      headers: { 'xi-api-key': AI33_KEY }, // FormData sets its own content type
      body: form,
    });
    const submitData = await submitRes.json();
    if (!submitData.success || !submitData.task_id) {
      throw new Error(`TTS submit failed: ${JSON.stringify(submitData).substring(0, 200)}`);
    }

    // Poll for result
    for (let i = 0; i < MAX_POLLS; i++) {
      if (i > 0) await new Promise(r => setTimeout(r, POLL_INTERVAL_MS));
      const pollRes = await fetch(`https://api.ai33.pro/v1/task/${submitData.task_id}`, { headers });
      if (!pollRes.ok) continue;
      const pollData = await pollRes.json();

      if (pollData.status === 'done' && pollData.metadata?.audio_url) {
        return {
          success: true,
          preview_url: pollData.metadata.audio_url,
          voice_id,
        };
      }
      if (pollData.status === 'error' || pollData.status === 'failed') {
        throw new Error(pollData.error_message || 'Preview generation failed');
      }
    }

    throw new Error('Preview timed out');
  } catch (error) {
    console.error('previewVoice error:', error.message);
    throw error instanceof HttpError ? error : new HttpError(500, error.message);
  }
};

export default handler;
