// @ts-nocheck -- faithful port from Deno JavaScript; remove during typed cleanup.
// Ported from the original hosted safeGeminiCall function
// Generated by migration/tools/port-fn.mjs; runtime adaptations reviewed.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import { geminiFetch } from '../lib/ai';
import type { FnHandler } from '../types';

// v2 — redeployed

async function safeGeminiCall(ctx, prompt, temperature = 0.8) {
  
  try {
    const response = await geminiFetch(ctx, '/v1beta/models/gemini-2.0-flash:generateContent', {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: { temperature, maxOutputTokens: 8192 }
        })
      });

    if (!response.ok) {
      const err = await response.json();
      throw new Error(`Gemini API Error ${response.status}: ${err.error?.message || "Unknown"}`);
    }

    const data = await response.json();

    if (!data.candidates || data.candidates.length === 0) {
      throw new Error("Gemini returned no candidates. Possibly content filtered.");
    }

    const text = data.candidates[0].content.parts[0].text;

    // Parse JSON from response (handle markdown code blocks)
    let jsonStr = text;
    if (text.includes("```json")) {
      jsonStr = text.split("```json")[1].split("```")[0].trim();
    } else if (text.includes("```")) {
      jsonStr = text.split("```")[1].split("```")[0].trim();
    }

    const parsed = JSON.parse(jsonStr);

    return { success: true, data: parsed, raw: text };
  } catch (error) {
    console.error("Gemini call failed:", error.message);
    return { success: false, error: error.message };
  }
}

const handler: FnHandler = async (body, ctx) => {
  try {
    const user = ctx.user;

    const { prompt, temperature } = body;
    if (!prompt) throw new HttpError(400, 'prompt required');

    const result = await safeGeminiCall(ctx, prompt, temperature || 0.8);
    return result;
  } catch (error) {
    throw new HttpError(500, error.message);
  }
};

export default handler;
