// @ts-nocheck -- faithful port from Deno JavaScript; remove during typed cleanup.
// Ported from base44/functions/scheduleClipPost.ts
// Generated by migration/tools/port-fn.mjs ; runtime adaptations reviewed.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import type { FnHandler } from '../types';

// v2 — uses UploadMetadata entity with record_type='scheduled_post'

const handler: FnHandler = async (body, ctx) => {
  const user = ctx.user;

  
  const action = body.action || 'schedule';

  // ── SCHEDULE — Create a single scheduled post ──────────────
  if (action === 'schedule') {
    const post = await ctx.db.UploadMetadata.create({
      record_type: 'scheduled_post',
      project_id: body.project_id || 'clip-extractor',
      title_primary: body.seo_title || '',
      description_template: body.seo_description || '',
      tags: body.seo_tags || '',
      hashtags: body.seo_hashtags || '',
      platform: body.platform || 'youtube_shorts',
      selected_channel_id: body.channel_setting_id || '',
      scheduled_at: body.scheduled_at || '',
      status: 'scheduled',
      privacy: body.privacy || 'public',
      video_url: body.video_url || '',
      clip_url: body.clip_url || '',
      clip_data: JSON.stringify(body.clip_data || {}),
      published_url: '',
      error_message: '',
      virality_score: body.virality_score || 0,
      user_email: user.email || '',
    });

    console.log('Scheduled post: ' + (body.seo_title || 'untitled') + ' for ' + body.scheduled_at);

    return {
      success: true,
      post_id: post.id,
      scheduled_at: body.scheduled_at,
    };
  }

  // ── BULK — Schedule multiple clips at once ─────────────────
  if (action === 'bulk') {
    const clips = body.clips || [];
    if (!clips.length) throw new HttpError(400, 'clips array required');

    const TIME_HOURS = { morning: 9, afternoon: 13, evening: 19, night: 21 };
    const strategy = body.strategy || 'spread';
    const hour = TIME_HOURS[body.time_slot] || 19;

    const baseDate = body.start_date ? new Date(body.start_date) : new Date();
    baseDate.setDate(baseDate.getDate() + 1);

    const results = [];

    for (let i = 0; i < clips.length; i++) {
      const clip = clips[i];
      const seo = clip.seo || {};

      var dayOffset = strategy === 'spread' ? i : Math.floor(i / 3);
      var inDayOffset = strategy === 'burst' ? (i % 3) * 2 : 0;

      const postDate = new Date(baseDate);
      postDate.setDate(postDate.getDate() + dayOffset);
      postDate.setHours(hour + inDayOffset, 0, 0, 0);
      const scheduledAt = postDate.toISOString();

      const post = await ctx.db.UploadMetadata.create({
        record_type: 'scheduled_post',
        project_id: 'clip-extractor',
        title_primary: seo.title || clip.clip_data?.title || 'Clip ' + (i + 1),
        description_template: seo.description || '',
        tags: (seo.tags || []).join(', '),
        hashtags: (seo.hashtags || []).map(function(h) { return '#' + h; }).join(' '),
        platform: clip.platform || 'youtube_shorts',
        selected_channel_id: body.channel_setting_id || '',
        scheduled_at: scheduledAt,
        status: 'scheduled',
        privacy: body.privacy || 'public',
        video_url: body.video_url || '',
        clip_url: clip.clip_url || '',
        clip_data: JSON.stringify(clip.clip_data || {}),
        published_url: '',
        error_message: '',
        virality_score: clip.clip_data?.virality_score || 0,
        user_email: user.email || '',
      });

      results.push({
        post_id: post.id,
        title: seo.title || 'Clip ' + (i + 1),
        scheduled_at: scheduledAt,
      });
    }

    console.log('Bulk scheduled ' + results.length + ' clips (' + strategy + ')');
    return { success: true, scheduled_count: results.length, posts: results };
  }

  // ── PROCESS — Check for due posts and publish them ─────────
  if (action === 'process') {
    const now = new Date().toISOString();

    const allPosts = await ctx.db.UploadMetadata.filter({
      record_type: 'scheduled_post',
      status: 'scheduled',
    });

    var readyPosts = (allPosts || []).filter(function(p) {
      return p.scheduled_at && new Date(p.scheduled_at) <= new Date(now);
    });

    if (readyPosts.length === 0) {
      return { success: true, processed: 0, message: 'No posts due' };
    }

    console.log('Found ' + readyPosts.length + ' posts due for publishing');
    const results = [];

    for (var pi = 0; pi < readyPosts.length; pi++) {
      const post = readyPosts[pi];
      try {
        // Publishing was dropped; due posts remain available for manual posting.
        await ctx.db.UploadMetadata.update(post.id, { status: 'ready_to_post' });
        results.push({ post_id: post.id, title: post.title_primary, status: 'ready_to_post' });
      } catch (err) {
        console.log('Failed to publish: ' + post.title_primary + ' - ' + err.message);
        await ctx.db.UploadMetadata.update(post.id, { status: 'failed', error_message: err.message });
        results.push({ post_id: post.id, title: post.title_primary, status: 'failed', error: err.message });
      }
    }

    return { success: true, processed: results.length, results: results };
  }

  // ── CANCEL ─────────────────────────────────────────────────
  if (action === 'cancel') {
    if (!body.post_id) throw new HttpError(400, 'post_id required');
    await ctx.db.UploadMetadata.update(body.post_id, { status: 'cancelled' });
    return { success: true, status: 'cancelled' };
  }

  // ── LIST — Get all scheduled posts ─────────────────────────
  if (action === 'list') {
    var posts;
    if (body.status) {
      posts = await ctx.db.UploadMetadata.filter({ record_type: 'scheduled_post', status: body.status });
    } else {
      posts = await ctx.db.UploadMetadata.filter({ record_type: 'scheduled_post' });
    }
    return { success: true, posts: posts || [], count: (posts || []).length };
  }

  throw new HttpError(400, 'Unknown action: ' + action);
};

export default handler;
