// Ported from base44/functions/selectHook/entry/entry.ts
// @ts-nocheck — temporary Phase 6 port debt; runtime behavior is preserved verbatim.
// Generated by migration/tools/port-fn.mjs; Phase 6 port review completed.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import { ownMediaHosts } from '../lib/storage';
import type { FnHandler } from '../types';


const handler: FnHandler = async (body, ctx) => {
  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Requested-With',
  };

  

  try {
    

    // ════════════════════════════════════════════════════════════
    // ACTION: proxyAsset — fetch and return base64 encoded asset
    // ════════════════════════════════════════════════════════════
    if (body.action === 'proxyAsset') {
      const url = body.url;

      if (!url || !url.startsWith('http')) {
        throw new HttpError(400, JSON.stringify({ success: false, error: 'Invalid URL' }));
      }

      const allowedDomains = [
        // AIQuickDraw domains
        'file.aiquickdraw.com',
        'tempfile.aiquickdraw.com',
        'cdn.aiquickdraw.com',
        
        // MyVoicify custom domains (R2)
        'myvoicify.app',
        'media.myvoicify.app',
        'files.myvoicify.app',
        'cdn.myvoicify.app',
        
        // R2/Cloudflare storage (fallback)
        'r2.dev',
        'r2.cloudflarestorage.com',
        'pub-aafc308ff5954f7187e75e4d90948e91.r2.dev',
        
        // Google storage
        'storage.googleapis.com',
        
        // AI service providers
        'api.kie.ai',
        'ideogram.ai',
        'oaidalleapiprodscus.blob.core.windows.net',
        'replicate.delivery',
        'pbxt.replicate.delivery'
      ];

      let hostname;
      try {
        hostname = new URL(url).hostname;
      } catch (e) {
        throw new HttpError(400, JSON.stringify({ success: false, error: 'Malformed URL: ' + url }));
      }

      // Plus our own storage host (R2 custom domain / Bunny CDN) — see lib/storage.ts.
      const isAllowed = [...allowedDomains, ...ownMediaHosts(ctx.env)].some(domain => {
        return hostname === domain || hostname.endsWith('.' + domain) || hostname.includes(domain);
      });

      if (!isAllowed) {
        console.log('Domain rejected:', hostname);
        throw new HttpError(403, JSON.stringify({ success: false, error: 'Domain not in allowlist: ' + hostname }));
      }

      try {
        console.log('Proxying:', url);

        const response = await fetch(url, {
          headers: {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            'Accept': '*/*',
          }
        });

        if (!response.ok) {
          throw new HttpError(502, JSON.stringify({ success: false, error: 'Upstream returned ' + response.status }));
        }

        const arrayBuffer = await response.arrayBuffer();
        const uint8Array = new Uint8Array(arrayBuffer);

        // Convert to base64
        let binary = '';
        const chunkSize = 8192;
        for (let i = 0; i < uint8Array.length; i += chunkSize) {
          const chunk = uint8Array.subarray(i, Math.min(i + chunkSize, uint8Array.length));
          for (let j = 0; j < chunk.length; j++) {
            binary += String.fromCharCode(chunk[j]);
          }
        }
        const base64Data = btoa(binary);

        const contentType = response.headers.get('content-type') || 'application/octet-stream';

        console.log('Proxy success:', url, 'Size:', uint8Array.length, 'Type:', contentType);

        return {
            success: true,
            data: base64Data,
            content_type: contentType,
            size: uint8Array.length
          };

      } catch (fetchError) {
        console.log('Fetch error:', fetchError.message);
        throw new HttpError(502, JSON.stringify({ success: false, error: 'Fetch failed: ' + fetchError.message }));
      }
    }

    // ════════════════════════════════════════════════════════════
    // ACTION: proxyAudio — stream audio directly with CORS headers
    // ════════════════════════════════════════════════════════════
    if (body.action === 'proxyAudio') {
      const url = body.url;

      if (!url || !url.startsWith('http')) {
        throw new HttpError(400, JSON.stringify({ success: false, error: 'Invalid URL' }));
      }

      try {
        const response = await fetch(url, {
          headers: {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            'Accept': 'audio/*,*/*',
          }
        });

        if (!response.ok) {
          throw new HttpError(502, JSON.stringify({ success: false, error: 'Upstream returned ' + response.status }));
        }

        const arrayBuffer = await response.arrayBuffer();
        const contentType = response.headers.get('content-type') || 'audio/wav';

        return new Response(arrayBuffer, {
          status: 200,
          headers: {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
            'Access-Control-Allow-Headers': '*',
            'Content-Type': contentType,
            'Content-Length': arrayBuffer.byteLength.toString(),
            'Cache-Control': 'public, max-age=31536000',
          }
        });

      } catch (fetchError) {
        throw new HttpError(502, JSON.stringify({ success: false, error: 'Fetch failed: ' + fetchError.message }));
      }
    }

    // ════════════════════════════════════════════════════════════
    // DEFAULT: selectHook action
    // ════════════════════════════════════════════════════════════
    const user = ctx.user;

    if (!user) {
      throw new HttpError(401, 'Unauthorized');
    }

    const { project_id, hook_id } = body;

    if (project_id && hook_id) {
      const all_hooks_list = await ctx.db.Hooks.list();
      const all_hooks = all_hooks_list.filter(h => h.project_id === project_id);

      for (const h of all_hooks) {
        if (h.is_selected) {
          await ctx.db.Hooks.update(h.id, { is_selected: false });
        }
      }

      await ctx.db.Hooks.update(hook_id, { is_selected: true });
    }

    return { success: true };

  } catch (error) {
    console.log('Error:', error.message);
    throw new HttpError(500, error.message);
  }
};

export default handler;
