// Ported from the original hosted sleepSceneBreakdown function
// @ts-nocheck — temporary Phase 6 port debt; runtime behavior is preserved verbatim.
// Generated by migration/tools/port-fn.mjs; Phase 6 port review completed.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import { anthropicFetch, geminiFetch, hasAiProvider } from '../lib/ai';
import type { FnHandler } from '../types';
import { stripTtsMarkers } from '../lib/scriptText';

// v5 — Gemini 2.5 Pro primary, Claude fallback, bulkCreate, max 12 scenes, code-controlled durations
// ══════════════════════════════════════════════════════════════════
// SLEEP VISUAL BREAKDOWN ENGINE (v5)
// ══════════════════════════════════════════════════════════════════
// Generates 6-12 ambient environment image definitions.
// Narration is split in code (not by AI) to avoid timeout.
// AI only generates visual concepts + image prompts.
// NO PEOPLE — pure environment/landscape scenes.
// Primary: Gemini 2.5 Pro | Fallback: Claude Sonnet
// ══════════════════════════════════════════════════════════════════

async function callGemini(ctx, prompt, temperature = 0.5) {
  if (!(await hasAiProvider(ctx, 'gemini'))) throw new Error("Gemini provider not available");

  const response = await geminiFetch(ctx, '/v1beta/models/gemini-2.5-pro:generateContent', {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        generationConfig: {
          temperature,
          maxOutputTokens: 6000,
          responseMimeType: "application/json"
        }
      })
    });

  if (!response.ok) {
    const err = await response.json();
    throw new Error(`Gemini error: ${err.error?.message || response.status}`);
  }

  const data = await response.json();
  const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!rawText) throw new Error("No response from Gemini");

  try { return JSON.parse(rawText); } catch (_) {
    const match = rawText.match(/\{[\s\S]*\}/);
    if (match) return JSON.parse(match[0]);
    throw new Error("Failed to parse Gemini JSON");
  }
}

async function callClaude(ctx, prompt, temperature = 0.5) {
  if (!(await hasAiProvider(ctx, 'anthropic'))) throw new Error("Anthropic provider not available");

  const response = await anthropicFetch(ctx, '/v1/messages', {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "anthropic-version": "2023-06-01"
    },
    body: JSON.stringify({
      model: "claude-sonnet-4-5",
      max_tokens: 6000,
      temperature,
      messages: [{ role: "user", content: prompt }]
    })
  });

  if (!response.ok) {
    const err = await response.json();
    throw new Error(`Claude error: ${err.error?.message || response.status}`);
  }

  const data = await response.json();
  const rawText = data.content?.[0]?.text;
  if (!rawText) throw new Error("No response from Claude");

  try { return JSON.parse(rawText); } catch (_) {
    const match = rawText.match(/\{[\s\S]*\}/);
    if (match) return JSON.parse(match[0]);
    throw new Error("Failed to parse Claude JSON");
  }
}

// Call Gemini first, fall back to Claude on any error
async function callAI(ctx, prompt, temperature = 0.5) {
  try {
    console.log("🤖 Calling Gemini 2.5 Pro...");
    const result = await callGemini(ctx, prompt, temperature);
    console.log("✅ Gemini succeeded");
    return { result, provider: "gemini" };
  } catch (geminiErr) {
    console.warn(`⚠️ Gemini failed: ${geminiErr.message} — falling back to Claude...`);
    try {
      const result = await callClaude(ctx, prompt, temperature);
      console.log("✅ Claude fallback succeeded");
      return { result, provider: "claude" };
    } catch (claudeErr) {
      throw new Error(`Both AI providers failed. Gemini: ${geminiErr.message} | Claude: ${claudeErr.message}`);
    }
  }
}

function cleanNarrationText(text) {
  if (!text) return text;
  let cleaned = text;
  cleaned = cleaned.replace(/\[[^\]]*\]/gi, (match) => {
    if (/PAUSE|BREATHE/i.test(match)) return match;
    return '';
  });
  cleaned = cleaned.replace(/^(VOICEOVER|NARRATOR|VO|SOUND|MUSIC|SFX|SCENE|V\.?O\.?)\s*:\s*/gim, '');
  cleaned = cleaned.replace(/^[A-Z\s]+\(V\.?O\.?\)\s*:?\s*/gim, '');
  cleaned = cleaned.replace(/\*\*[^*]+\*\*:?\s*/g, '');
  cleaned = cleaned.replace(/\*\*/g, '');
  cleaned = cleaned.replace(/\*/g, '');
  cleaned = cleaned.replace(/\n{2,}/g, ' ').replace(/\s{2,}/g, ' ').trim();
  return cleaned;
}

// Split script into N roughly-equal chunks, breaking at sentence boundaries
function splitScriptIntoChunks(scriptText, chunkCount) {
  const sentences = scriptText.split(/(?<=[.!?…])\s+/).filter(s => s.trim().length > 0);
  const totalSentences = sentences.length;
  const perChunk = Math.ceil(totalSentences / chunkCount);
  const chunks = [];
  for (let i = 0; i < chunkCount; i++) {
    const start = i * perChunk;
    const end = Math.min(start + perChunk, totalSentences);
    chunks.push(sentences.slice(start, end).join(' '));
  }
  return chunks;
}

const handler: FnHandler = async (body, ctx) => {
  const callStart = Date.now();
  try {
    const user = ctx.user;

    const { project_id } = body;

    const projects = await ctx.db.Projects.filter({ id: project_id });
    const project = projects[0];
    if (!project) throw new HttpError(404, 'Project not found');

    const allScripts = await ctx.db.Scripts.filter({ project_id });
    const script = allScripts.find(s => s.version === 'final_aggregated');
    if (!script?.full_script) {
      throw new HttpError(400, 'No final script found.');
    }

    const isMeditation = project.project_mode === 'sleep_meditation';
    const finalScript = stripTtsMarkers(script.full_script);
    const wordCount = finalScript.split(/\s+/).filter(w => w.length > 0).length;
    const durationMinutes = project.video_duration_minutes || Math.ceil(wordCount / 150);

    // Scene count — 1 per 5 min, floor 6, hard cap 12
    const imageCount = Math.min(12, Math.max(6, Math.round(durationMinutes / 5)));

    // Durations computed purely in code — AI has no say
    const durationSecPerScene = (durationMinutes * 60) / imageCount;

    console.log(`🌙 Sleep ambient breakdown: ${durationMinutes}min → ${imageCount} scenes @ ${(durationSecPerScene / 60).toFixed(1)}min each | mode: ${project.project_mode}`);

    // Delete old scenes in parallel
    const oldScenes = await ctx.db.Scenes.filter({ project_id });
    if (oldScenes.length > 0) {
      await Promise.all(oldScenes.map(s => ctx.db.Scenes.delete(s.id).catch(() => {})));
      console.log(`🗑️ Deleted ${oldScenes.length} old scenes`);
    }

    // Split narration in code — don't ask AI to do it
    const narrationChunks = splitScriptIntoChunks(finalScript, imageCount);

    const prompt = `You are a visual art director for premium sleep content. Design ${imageCount} ambient environment images for a ${durationMinutes}-minute ${isMeditation ? 'guided meditation' : 'sleep story'} about "${project.name}".

RULES:
- Dark moody oil painting style, Rembrandt chiaroscuro, 70%+ shadow
- Colors: deep amber, burnt sienna, dark chocolate, midnight navy, warm gold highlights only
- Light sources: very dim candlelight, very dim moonlight, faint distant glow, dying campfire embers — always warm and VERY DIM
- Topic-matched to "${project.name}" — every image relates to the topic
- Progressive darkening: scene 1 has very dim warm glow, final scenes are nearly black
- ALL light must be described as "very dim" or "faint" — never just "candlelight" or "moonlight" alone
- Simple compositions with lots of dark negative space

ABSOLUTE PROHIBITION — ZERO TOLERANCE:
- NEVER include ANY human figures, people, persons, characters, silhouettes, or shadows of people
- NEVER include ANY body parts: hands, fingers, feet, legs, arms, face, eyes, skin, torso, shoulders, hair, lips, head
- NEVER include human-occupied furniture: beds, chairs, sofas, desks with items on them
- NEVER include clothing, shoes, accessories, or any object implying human presence
- NEVER use words like: person, figure, someone, viewer, listener, character, protagonist, woman, man, child
- Every scene must be a PURE ENVIRONMENT or LANDSCAPE — nature, architecture, still life, abstract atmosphere
- If the topic involves people, represent it through SYMBOLIC environments (empty paths, distant lights, weathered doors) — NEVER through human forms

Return JSON with EXACTLY ${imageCount} scenes and nothing else — no markdown, no backticks, no explanation:
{
  "scenes": [
    {
      "scene_number": 1,
      "image_prompt_core": "Pure environment/landscape prompt with NO people or body parts. Example: 'A misty forest path at twilight, ancient oak trees with gnarled roots, golden fireflies drifting through heavy fog, dark moody oil painting, Rembrandt chiaroscuro lighting, deep shadow, warm amber rim light, burnt sienna and dark chocolate palette, low-key lighting, masterpiece quality, 70 percent shadow'",
      "camera_movement": "ultra_slow_zoom_in",
      "mood": "2-3 words"
    }
  ]
}

camera_movement must be one of: ultra_slow_zoom_in, ultra_slow_zoom_out, ultra_slow_pan_left, ultra_slow_pan_right
Alternate camera movements across scenes for visual variety.`;

    console.log(`🎨 Generating ${imageCount} ambient image definitions...`);
    const { result, provider } = await callAI(ctx, prompt, 0.6);

    let scenesArr = result?.scenes;
    if (!scenesArr || !Array.isArray(scenesArr)) {
      console.error(`No scenes array. Keys: ${Object.keys(result || {}).join(',')}`);
      throw new HttpError(500, 'AI failed to generate ambient images');
    }

    // Safety net — never exceed imageCount even if AI returns extras
    scenesArr = scenesArr.slice(0, imageCount);

    // Beat timing — all computed in code, perfectly even
    const beatDurations = Array(imageCount).fill(durationSecPerScene);
    const beatStartTimes = beatDurations.map((_, i) => i * durationSecPerScene);

    // Save ProductionSettings
    const psPayload = {
      beat_durations: JSON.stringify(beatDurations),
      beat_start_times: JSON.stringify(beatStartTimes),
      story_analysis: JSON.stringify({
        central_theme: `${isMeditation ? 'Guided meditation' : 'Sleep story'}: ${project.name}`,
        narrative_arc_summary: 'Progressive relaxation with topic-matched ambient visuals',
        emotional_trajectory: ['wonder', 'calm', 'settling', 'deep_rest'],
        visual_world: `Dreamlike ambient scenes inspired by ${project.name}`,
        recurring_visual_motifs: ['warm light', 'gentle darkness', 'nature', 'atmosphere'],
        color_arc: 'warm amber → deep blue → midnight → near-darkness',
        visual_format: 'ambient_images_with_ken_burns',
        ai_provider: provider
      })
    };
    const psList = await ctx.db.ProductionSettings.filter({ project_id });
    if (psList[0]) {
      await ctx.db.ProductionSettings.update(psList[0].id, psPayload);
    } else {
      await ctx.db.ProductionSettings.create({ project_id, ...psPayload });
    }

    // bulkCreate instead of sequential creates
    const sceneRecords = scenesArr.map((aiScene, i) => {
      const cleanedNarration = cleanNarrationText(narrationChunks[i] || '');
      const directorNotes = {
        image_prompt_core: aiScene.image_prompt_core || '',
        camera_movement: aiScene.camera_movement || 'ultra_slow_zoom_out',
        mood: aiScene.mood || 'serene',
        duration_minutes: parseFloat((durationSecPerScene / 60).toFixed(2)),
        emotional_intensity: 0.15,
        sleep_visual_type: 'ambient_image',
        phase: 'sleep_ambient'
      };
      return {
        project_id,
        scene_number: i + 1,
        narration_text: cleanedNarration,
        image_prompt: `DIRECTOR_NOTES:${JSON.stringify(directorNotes)}`,
        animation_prompt: aiScene.camera_movement || 'ultra_slow_zoom_out',
        duration_seconds: durationSecPerScene,
        camera_movement: 'slow_zoom_out',
        animation_speed: 'very_slow',
        status: 'breakdown_ready'
      };
    });

    await ctx.db.Scenes.bulkCreate(sceneRecords);

    await ctx.db.Projects.update(project_id, {
      status: 'breakdown_complete',
      current_step: 5
    });

    const elapsed = ((Date.now() - callStart) / 1000).toFixed(1);
    console.log(`🌙 Created ${sceneRecords.length} ambient scenes in ${elapsed}s via ${provider}`);
    console.log(`📊 Each scene: ${(durationSecPerScene / 60).toFixed(1)}min | Total: ${durationMinutes}min`);

    return {
      success: true,
      done: true,
      scenes_created: sceneRecords.length,
      total_target: imageCount,
      scene_duration_minutes: parseFloat((durationSecPerScene / 60).toFixed(2)),
      total_duration_minutes: durationMinutes,
      beat_durations: beatDurations,
      beat_start_times: beatStartTimes,
      visual_format: 'ambient_images_with_ken_burns',
      ai_provider: provider
    };

  } catch (error) {
    console.error('❌ sleepSceneBreakdown error:', error.message);
    throw error instanceof HttpError ? error : new HttpError(500, error.message);
  }
};

export default handler;
