// Ported from the original hosted submitTranscription function
// Generated by migration/tools/port-fn.mjs — prompt strings remain unchanged.

import { HttpError } from '../lib/http';
import { submit as asrSubmit } from '../lib/asr';
import type { FnHandler } from '../types';

// v5 — all paths synced, correct AssemblyAI API fields

// ══════════════════════════════════════════════════════════════════
// SUBMIT TRANSCRIPTION — Start selected ASR backend, return opaque ID
// ══════════════════════════════════════════════════════════════════

const handler: FnHandler = async (body, ctx) => {
  const { voiceover_url } = body;
  if (!voiceover_url) throw new HttpError(400, 'voiceover_url required');

  const { transcript_id } = await asrSubmit(ctx, voiceover_url);
  console.log(`📡 Transcription submitted: ${transcript_id}`);
  return { success: true, transcript_id };
};

export default handler;
