// Ported from the original hosted thumbnailBlend function
// @ts-nocheck — temporary Phase 7 port debt; runtime behavior is preserved verbatim.
// Generated by migration/tools/port-fn.mjs; Phase 7 port review completed.
// Prompt strings are copied byte-for-byte. Prove it: tools/verify-prompts.mjs

import { HttpError } from '../lib/http';
import { editImage, recordInfo } from '../lib/kie';
import { ingestUrl } from '../lib/storage';
import type { FnHandler } from '../types';

// v2 — redeployed
// thumbnailBlend — KIE Seedream image editing/compositing
// Takes a generated thumbnail as reference + character/object images → blends them

const wait = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

const handler: FnHandler = async (body, ctx) => {
  try {
    const {
      reference_image_url,
      face_images = [],
      object_images = [],
      background_image_url,
      video_title = '',
      custom_instructions = '',
      concept_id,
    } = body;

    if (!reference_image_url) {
      throw new HttpError(400, 'reference_image_url is required');
    }

    console.log('=== thumbnailBlend (KIE Seedream) ===');
    console.log(`Reference: ${reference_image_url.substring(0, 80)}`);
    console.log(`Face images: ${face_images.length}`);
    console.log(`Object images: ${object_images.length}`);
    console.log(`Background: ${background_image_url ? 'yes' : 'no'}`);

    const allInputImages = [reference_image_url];
    for (const faceUrl of face_images) if (faceUrl) allInputImages.push(faceUrl);
    if (background_image_url) allInputImages.push(background_image_url);
    for (const objectUrl of object_images) if (objectUrl) allInputImages.push(objectUrl);

    const tasks = [];
    if (face_images.length > 0) tasks.push('Replace the subject face with the exact face from the character reference photo, matching lighting and skin tone seamlessly');
    if (background_image_url) tasks.push('Replace the background with the provided background image, apply cinematic depth-of-field blur');
    if (object_images.length > 0) tasks.push('Replace props/objects with the provided replacement images, maintain position and scale');
    if (custom_instructions) tasks.push(custom_instructions.substring(0, 150));

    const prompt = `Photo editing task. Preserve the original thumbnail composition, pose, framing, and text overlays exactly. ${tasks.length > 0 ? tasks.join('. ') + '.' : 'Enhance realism and blending.'} Photorealistic YouTube thumbnail, high contrast, sharp subject, consistent lighting, seamless compositing, no AI artifacts. 1920x1080 16:9.`;

    console.log(`Prompt length: ${prompt.length} chars`);
    console.log(`Total input images: ${allInputImages.length}`);

    const taskId = await editImage(ctx, {
      prompt,
      image_url: reference_image_url,
      image_urls: allInputImages,
      aspect_ratio: '16:9',
      resolution: '2K',
    });
    console.log(`✅ KIE task submitted: ${taskId}`);

    const startTime = Date.now();
    const maxPollMs = 85_000;
    let finalUrl: string | null = null;

    while (Date.now() - startTime < maxPollMs) {
      await wait(5_000);
      const record = await recordInfo(ctx, taskId);
      if (record.state === 'success') {
        finalUrl = record.url;
        break;
      }
      if (record.state === 'fail') throw new Error(record.failMsg || 'Blend task failed');
    }

    if (!finalUrl) {
      return {
        success: false,
        pending: true,
        task_id: taskId,
        concept_id,
        message: 'Blend in progress. Poll with pollThumbnailBlend.',
      };
    }

    const stored = await ingestUrl(ctx, finalUrl, {
      tier: 'durable',
      prefix: `thumbnails/${concept_id || 'blend'}`,
    });

    if (concept_id) {
      try {
        await ctx.db.ThumbnailConcepts.update(concept_id, { image_url: stored.url });
        console.log('✅ Updated concept with blended image');
      } catch (error) {
        console.warn('Failed to update concept:', error.message);
      }
    }

    return {
      success: true,
      image_url: stored.url,
      task_id: taskId,
      concept_id,
    };
  } catch (error) {
    console.error('thumbnailBlend error:', error.message);
    throw error instanceof HttpError ? error : new HttpError(500, error.message);
  }
};

export default handler;
